# SuavoAgent -- Zero-Config One-Paste Installer
#
# INSTALL (paste into Admin PowerShell):
#   Set-ExecutionPolicy Bypass -Scope Process -Force; irm https://raw.githubusercontent.com/MinaH153/SuavoAgent/main/bootstrap.ps1 -OutFile $env:TEMP\bs.ps1; & $env:TEMP\bs.ps1
#
# By default resolves the latest published release from GitHub. To pin a
# specific version (e.g. for rollback testing), pass -ReleaseTag v3.10.5.
#
# What it does:
# 1. Detects pharmacy management system (PioneerRx, or none)
# 2. Discovers SQL credentials if PMS found
# 3. Downloads signed agent binaries from GitHub
# 4. Writes appsettings.json with discovered credentials
# 5. Installs + starts Windows services
# 6. Agent auto-discovers PMS during learning phase if not detected at install
#
# SAFETY: ConnectionStringServer is called ONCE. Agent uses MaxPoolSize=1.
# Never disrupts pharmacy operations.

param(
    [string]$PharmacyId,
    [string]$ApiKey,
    [string]$AgentId,
    # Single-use install token generated by the dashboard. When provided, the
    # bootstrap calls /api/agent/register to exchange it for a pharmacy-scoped
    # API key + pharmacy id instead of requiring them up-front. This is the
    # path used by the dashboard onboarding flow.
    [object]$InstallToken,
    [string]$CloudUrl = "https://suavollc.com",
    [switch]$LearningMode,
    # Empty = auto-resolve the latest published release via the GitHub API.
    # Pass an explicit v-tag (e.g. -ReleaseTag v3.10.5) to pin a version.
    [string]$ReleaseTag = "",
    [string]$RepoOwner = "MinaH153",
    [string]$RepoName = "SuavoAgent",
    [switch]$SkipConsent,
    # Re-apply service registration + ACLs without touching operator config,
    # SQL credentials, or consent receipt. Triggered by SuavoAgent.Watchdog
    # when Core/Broker fail to recover via sc.exe start alone.
    [switch]$Repair,
    # 2026-05-03: founder dogfood / internal sandbox install. Set by the
    # cloud's /api/agent/quick-install endpoint when the install token's
    # pharmacy has is_internal_sandbox=true. Auto-fills MKM Internal
    # consent + skips SQL/PMS prompts (sandbox doesn't run PioneerRx).
    # Trusted because the cloud already validated the token bears
    # is_internal_sandbox before passing this flag.
    [switch]$SandboxBypass
)

# Auto-log everything -- transcript saved to desktop for debugging
$transcriptPath = "$env:USERPROFILE\Desktop\suavo-install-$(Get-Date -Format 'yyyyMMdd-HHmmss').log"
Start-Transcript -Path $transcriptPath -Force | Out-Null

$ErrorActionPreference = "Stop"
$installDir = "C:\Program Files\Suavo\Agent"
$dataDir = "$env:ProgramData\SuavoAgent"
# Single source of truth for installerVersion in the consent receipt. Bump
# alongside any tag release so the audit trail reflects which bootstrap
# wrote the receipt. Two prior literals (3.8.0 / 3.9.1) were left stale.
$bootstrapVersion = "3.14.5"
# Persisted across reinstalls. The cleanup path keeps these so consent +
# learned-state survive a re-run (Trip A 2026-04-25: pharmacist re-typed
# consent 4x because state.db AND consent-receipt.json were both wiped).
#
# state.key MUST stay alongside state.db -- AgentStateDb opens state.db with
# the encryption key from state.key, and Program.cs only generates a new key
# when state.key is missing. If we keep state.db but wipe state.key, the new
# key won't decrypt the existing DB and AgentStateDb wipes it as 'unreadable'.
# Codex flagged this as a CRITICAL state-loss risk on PR #23 review.
$dataDirKeepList = @('logs', 'consent-receipt.json', 'state.db', 'state.key', 'download-cache', 'actuation.json', 'pioneerrx.json', 'vision.json')
$script:BootstrapStartedAt = Get-Date
$script:CurrentInstallStage = "bootstrap_start"
$script:InstallTelemetryToken = $null

function ConvertTo-PlainTextSecret {
    param([object]$Secret)
    if ($null -eq $Secret) { return $null }
    if ($Secret -is [System.Security.SecureString]) {
        $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Secret)
        try {
            return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
        } finally {
            [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
        }
    }
    return [string]$Secret
}

function Normalize-InstallTelemetryStage {
    param([AllowNull()][string]$StageText)

    $stage = if ([string]::IsNullOrWhiteSpace($StageText)) { "" } else { $StageText.ToLowerInvariant() }
    $normalized = $stage -replace '[^a-z0-9_\-]', '_'
    $knownStages = @(
        "preflight_admin",
        "repair_preflight",
        "release_resolve",
        "data_acl",
        "checksum_download",
        "signature_verify",
        "download_binary",
        "download_hash",
        "cloud_register",
        "cloud_auth_verify",
        "service_start_core",
        "service_start_broker",
        "service_start_watchdog",
        "service_verify"
    )
    if ($knownStages -contains $normalized) { return $normalized }
    if ($stage -match 'admin') { return "preflight_admin" }
    if ($stage -match 'repair') { return "repair_preflight" }
    if ($stage -match 'detect|pharmacy management|pms') { return "pms_detect" }
    if ($stage -match 'sql') { return "sql_discovery" }
    if ($stage -match 'download|checksum|signature|hash') { return "download" }
    if ($stage -match 'disk|bitlocker|encryption') { return "disk_encryption" }
    if ($stage -match 'config|writing configuration') { return "configuration" }
    if ($stage -match 'register|cloud|install token') { return "cloud_register" }
    if ($stage -match 'installing windows services|service registered') { return "service_install" }
    if ($stage -match 'watchdog') { return "service_start_watchdog" }
    if ($stage -match 'broker') { return "service_start_broker" }
    if ($stage -match 'core|service|startup') { return "service_start_core" }
    if ($stage -match 'verify') { return "service_verify" }
    return "bootstrap"
}

function Redact-InstallTelemetryText {
    param([AllowNull()][string]$Text)
    if ($null -eq $Text) { return "" }

    $redacted = [string]$Text
    $redacted = $redacted -replace 'sai_[0-9a-fA-F]{24,}', '[REDACTED_INSTALL_TOKEN]'
    $redacted = $redacted -replace '(?i)\b(apiKey|installToken|authorization|password|passwd|pwd|secret|token)\s*[:=]\s*[^;\s,\r\n]+', '$1=[REDACTED_SECRET]'
    $redacted = $redacted -replace '(?i)\b(User ID|UID|Password|PWD)\s*=\s*[^;\r\n]+', '$1=[REDACTED_SECRET]'
    $redacted = $redacted -replace '([\\/])Users([\\/])[^\\/\r\n]+', '$1Users$2[REDACTED_USER]'
    $redacted = $redacted -replace '([\\/])home([\\/])[^\\/\r\n]+', '$1home$2[REDACTED_USER]'
    $redacted = $redacted -replace '\b\d{3}-\d{2}-\d{4}\b', '[REDACTED_SSN]'
    $redacted = $redacted -replace '\bRx#?\s*\d{7,12}\b', '[REDACTED_RX]'
    $redacted = $redacted -replace '\b\d{3}[-.\s]\d{3}[-.\s]\d{4}\b', '[REDACTED_PHONE]'
    $redacted = $redacted -replace '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', '[REDACTED_EMAIL]'
    $redacted = $redacted -replace '\bMRN[:\s#]?\s*\d+\b', '[REDACTED_MRN]'
    $redacted = $redacted -replace '\b(0?[1-9]|1[0-2])/(0?[1-9]|[12]\d|3[01])/(19|20)\d{2}\b', '[REDACTED_DATE]'
    $redacted = $redacted -replace '"[^"]{65,}"', '"[REDACTED_LONG_STRING]"'

    if ($redacted.Length -gt 32000) {
        return $redacted.Substring($redacted.Length - 32000)
    }
    return $redacted
}

function Get-InstallTelemetryOsVersion {
    try {
        $os = Get-CimInstance -ClassName Win32_OperatingSystem -ErrorAction Stop
        if ($os.Caption) { return [string]$os.Caption }
    } catch { }
    return [Environment]::OSVersion.VersionString
}

function Get-InstallTelemetryMetadata {
    $metadata = @{}
    if ($pmsType) {
        $pms = ([string]$pmsType).ToLowerInvariant()
        if ($pms -match 'pioneer') { $metadata.pms = "pioneerrx" }
        else { $metadata.pms = "unknown" }
    } else {
        $metadata.pms = "unknown"
    }
    if (-not [string]::IsNullOrWhiteSpace($sqlServer)) {
        $metadata.sql_server_reachable = $true
        if ($sqlServer -match ',(\d+)$') {
            $metadata.sql_server_port = [int]$Matches[1]
        }
    }
    return $metadata
}

function Get-InstallTelemetryToken {
    if (-not [string]::IsNullOrWhiteSpace($script:InstallTelemetryToken)) {
        return $script:InstallTelemetryToken
    }
    $plain = ConvertTo-PlainTextSecret $InstallToken
    if (-not [string]::IsNullOrWhiteSpace($plain)) {
        $script:InstallTelemetryToken = $plain
    }
    return $script:InstallTelemetryToken
}

function Send-InstallTelemetry {
    param(
        [AllowNull()][string]$Stage = $script:CurrentInstallStage,
        [ValidateSet("info", "warn", "error", "fatal")][string]$Level = "error",
        [string]$Message = "SuavoAgent installer failed",
        [int]$ExitCode = 1,
        [AllowNull()][string]$StdoutTail,
        [hashtable]$Metadata
    )

    try {
        $token = Get-InstallTelemetryToken
        if ([string]::IsNullOrWhiteSpace($token)) { return }

        $body = @{
            install_token = $token
            stage = Normalize-InstallTelemetryStage -StageText $Stage
            level = $Level
            message = Redact-InstallTelemetryText -Text $Message
            exit_code = $ExitCode
            machine_name = $env:COMPUTERNAME
            os_version = Get-InstallTelemetryOsVersion
            duration_ms = [int]([math]::Min(86400000, [math]::Max(0, ((Get-Date) - $script:BootstrapStartedAt).TotalMilliseconds)))
        }

        if (-not [string]::IsNullOrWhiteSpace($StdoutTail)) {
            $body.stdout_tail = Redact-InstallTelemetryText -Text $StdoutTail
        }
        if (-not [string]::IsNullOrWhiteSpace($ReleaseTag)) {
            $body.agent_version_target = $ReleaseTag.TrimStart('v')
        }

        $safeMetadata = if ($Metadata) { $Metadata } else { Get-InstallTelemetryMetadata }
        if ($safeMetadata -and $safeMetadata.Count -gt 0) { $body.metadata = $safeMetadata }

        $json = $body | ConvertTo-Json -Depth 5
        $cloudBase = ([string]$CloudUrl).TrimEnd([char[]]"/")
        Invoke-RestMethod `
            -Uri "$cloudBase/api/agent/install-telemetry" `
            -Method POST `
            -ContentType "application/json" `
            -Body $json `
            -TimeoutSec 15 | Out-Null
    } catch {
        Write-Host "    Install telemetry skipped: $(Redact-InstallTelemetryText -Text $_.Exception.Message)" -ForegroundColor DarkGray
    }
}

function Read-ExistingAgentConfig {
    $configPath = Join-Path $installDir "appsettings.json"
    if (-not (Test-Path $configPath -PathType Leaf)) {
        return $null
    }

    try {
        $existingConfig = Get-Content -Path $configPath -Raw | ConvertFrom-Json
        if ($existingConfig.Agent) {
            return $existingConfig.Agent
        }
    } catch {
        Write-Host "  Existing appsettings.json could not be reused: $($_.Exception.Message)" -ForegroundColor DarkGray
    }

    return $null
}

# ============================================
# IDEMPOTENT CLEANUP -- runs before consent so a single
#   irm "https://.../bootstrap.ps1?v=$(Get-Random)" | iex
# always produces a known-good install, even over a broken one.
# ============================================
function Test-PriorInstall {
    $services = @("SuavoAgent.Core", "SuavoAgent.Broker", "SuavoAgent.Watchdog")
    foreach ($s in $services) {
        if (Get-Service -Name $s -ErrorAction SilentlyContinue) { return $true }
    }
    if (Test-Path $installDir) { return $true }
    if (Test-Path $dataDir)    { return $true }
    return $false
}

function Invoke-PriorInstallCleanup {
    Write-Host ""
    Write-Host "  Prior SuavoAgent install detected -- cleaning up before reinstall" -ForegroundColor Yellow
    foreach ($s in @("SuavoAgent.Watchdog", "SuavoAgent.Broker", "SuavoAgent.Core")) {
        $svc = Get-Service -Name $s -ErrorAction SilentlyContinue
        if ($svc) {
            if ($svc.Status -eq 'Running' -or $svc.Status -eq 'StartPending') {
                try { Stop-Service $s -Force -ErrorAction Stop } catch { }
                Start-Sleep -Seconds 2
            }
            sc.exe delete $s 2>$null | Out-Null
        }
    }
    # Helper.exe is a child process spawned by Core/Watchdog (NOT a Windows
    # service), so service stops don't kill it. Without this, Phase 3 binary
    # downloads fail with "file is being used by another process" because the
    # running Helper holds a file lock on Helper.exe in $installDir.
    # Caught at Nadim's pharmacy 2026-04-25 reinstall attempt.
    try {
        $orphans = Get-Process -ErrorAction SilentlyContinue | Where-Object {
            $_.ProcessName -like "SuavoAgent.*"
        }
        foreach ($p in $orphans) {
            Write-Host "    Killing orphan process $($p.ProcessName) (PID $($p.Id))" -ForegroundColor Yellow
            try { Stop-Process -Id $p.Id -Force -ErrorAction Stop } catch { }
        }
    } catch { }
    # Wait a beat for SCM to release handles before removing the binaries.
    Start-Sleep -Seconds 2
    if (Test-Path $installDir) {
        try { Remove-Item $installDir -Recurse -Force -ErrorAction Stop }
        catch { Write-Host "    (install dir cleanup had a hiccup: $($_.Exception.Message) -- continuing)" -ForegroundColor DarkGray }
    }
    if (Test-Path $dataDir) {
        # Keep the well-known artifacts that should survive a reinstall:
        #   logs/                 -- previous startup-crash.log for ops
        #   consent-receipt.json  -- avoids re-typing consent on reinstall
        #   state.db              -- preserves encrypted learning state
        # Everything else goes (config-overrides.json, lockfiles, etc.).
        Get-ChildItem $dataDir -Force -ErrorAction SilentlyContinue | Where-Object {
            $dataDirKeepList -notcontains $_.Name
        } | ForEach-Object {
            try { Remove-Item $_.FullName -Recurse -Force -ErrorAction Stop } catch { }
        }
    }
    Write-Host "  Cleanup complete -- proceeding with fresh install" -ForegroundColor Green
    Write-Host ""
}

function Invoke-LegacyNodeAgentQuarantine {
    $legacyDir = "C:\SuavoAgent"
    if (Test-Path $legacyDir) {
        $suffix = Get-Date -Format "yyyyMMdd-HHmmss"
        $target = "C:\SuavoAgent.quarantine-$suffix"
        Write-Host "  Legacy Node-era install detected at $legacyDir -- quarantining to $target" -ForegroundColor Yellow
        try {
            Rename-Item -Path $legacyDir -NewName ("SuavoAgent.quarantine-$suffix") -ErrorAction Stop
        } catch {
            Write-Host "    Could not quarantine ${legacyDir}: $($_.Exception.Message)" -ForegroundColor Yellow
        }
    }

    try {
        $tasks = Get-ScheduledTask -ErrorAction Stop | Where-Object {
            $_.TaskName -like "*SuavoAgent*" -or
            ($_.Actions | Where-Object {
                ($_.Execute -match "node|powershell|pwsh") -and
                (($_.Arguments -match "SuavoAgent") -or ($_.Execute -match "SuavoAgent"))
            })
        }
        foreach ($task in $tasks) {
            Write-Host "  Quarantining legacy scheduled task $($task.TaskPath)$($task.TaskName)" -ForegroundColor Yellow
            try {
                Unregister-ScheduledTask -TaskName $task.TaskName -TaskPath $task.TaskPath -Confirm:$false -ErrorAction Stop
            } catch {
                Write-Host "    Could not remove task $($task.TaskName): $($_.Exception.Message)" -ForegroundColor Yellow
            }
        }
    } catch {
        Write-Host "  Scheduled task scan skipped: $($_.Exception.Message)" -ForegroundColor DarkGray
    }
}

# -- Require Admin before touching existing install --
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "  [FAIL] Run as Administrator" -ForegroundColor Red
    Send-InstallTelemetry -Stage "preflight_admin" -Level "fatal" -Message "Installer was not run as Administrator" -ExitCode 1
    exit 1
}

if ($Repair) {
    Write-Host ""
    Write-Host "  SuavoAgent --repair mode" -ForegroundColor Yellow
    Write-Host "  Re-applying service registration + ACLs (no reinstall, no config touch)" -ForegroundColor DarkGray
    Write-Host ""

    # Re-assert install dir ACLs. If dir is missing we can't repair -- that's an
    # uninstall-scale problem, not a repair one.
    if (-not (Test-Path $installDir)) {
        Write-Host "  [FAIL] Install dir missing ($installDir) -- full reinstall required, --repair cannot fix this" -ForegroundColor Red
        Send-InstallTelemetry -Stage "repair_preflight" -Level "fatal" -Message "Install dir missing; --repair cannot continue" -ExitCode 1
        exit 1
    }
    try {
        $dirAcl = Get-Acl $installDir
        $dirAcl.SetAccessRuleProtection($true, $false)
        $dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
            "BUILTIN\Administrators", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")))
        $dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\SYSTEM", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")))
        $dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\LOCAL SERVICE", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow")))
        $dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\NETWORK SERVICE", "ReadAndExecute", "ContainerInherit,ObjectInherit", "None", "Allow")))
        # Phase 5.6: Helper now spawns into the user's interactive session via
        # CreateProcessAsUser. The .NET single-file apphost calls realpath() on
        # SuavoAgent.Helper.exe at startup, which opens the EXE as the running
        # user; without Users:RX the open fails and Helper crashes with
        # "Failed to resolve full path of the current executable" (Event 1023).
        $dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
            "BUILTIN\Users", "ReadAndExecute", "ContainerInherit,ObjectInherit", "None", "Allow")))
        Set-Acl $installDir $dirAcl
        Write-Host "  Install dir ACLs re-applied" -ForegroundColor Green
    } catch {
        Write-Host "  Install dir ACL repair failed: $($_.Exception.Message)" -ForegroundColor Yellow
    }

    # Re-register any missing services against the existing binaries.
    $serviceSpecs = @(
        @{ Name = 'SuavoAgent.Core';     Exe = 'SuavoAgent.Core.exe';     Account = 'NT AUTHORITY\LocalService';   Depends = $null;              Desc = 'Suavo pharmacy agent - SQL polling, cloud sync' },
        @{ Name = 'SuavoAgent.Broker';   Exe = 'SuavoAgent.Broker.exe';   Account = 'LocalSystem';                 Depends = 'SuavoAgent.Core';  Desc = 'Suavo pharmacy agent - session broker (LocalSystem for CreateProcessAsUser)' },
        @{ Name = 'SuavoAgent.Watchdog'; Exe = 'SuavoAgent.Watchdog.exe'; Account = 'LocalSystem';                 Depends = $null;              Desc = 'Suavo pharmacy agent - process watchdog' }
    )

    # Phase 5.6: re-pin dataDir ACL to include INTERACTIVE so Helper running as
    # the logged-in user can read state.db/state.key/configs and write logs.
    # Pre-3.14.1 installs locked dataDir to services-only, which crashed Helper
    # on startup (.NET 1023 "Failed to resolve full path" / log open denied).
    if (Test-Path $dataDir) {
        try {
            $repairDataAcl = Get-Acl $dataDir
            $repairDataAcl.SetAccessRuleProtection($true, $false)
            $repairRules = @(
                (New-Object System.Security.AccessControl.FileSystemAccessRule(
                    "NT AUTHORITY\SYSTEM", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")),
                (New-Object System.Security.AccessControl.FileSystemAccessRule(
                    "BUILTIN\Administrators", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")),
                (New-Object System.Security.AccessControl.FileSystemAccessRule(
                    "NT AUTHORITY\LOCAL SERVICE", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")),
                (New-Object System.Security.AccessControl.FileSystemAccessRule(
                    "NT AUTHORITY\NETWORK SERVICE", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow")),
                (New-Object System.Security.AccessControl.FileSystemAccessRule(
                    "NT AUTHORITY\INTERACTIVE", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow"))
            )
            foreach ($rule in $repairRules) { $repairDataAcl.AddAccessRule($rule) }
            Set-Acl $dataDir $repairDataAcl
            Write-Host "  Data dir ACL re-pinned with INTERACTIVE Modify (Phase 5.6)" -ForegroundColor Green
        } catch {
            Write-Host "  Data dir ACL re-pin failed: $($_.Exception.Message)" -ForegroundColor Yellow
        }
    }
    foreach ($spec in $serviceSpecs) {
        $exePath = Join-Path $installDir $spec.Exe
        if (-not (Test-Path $exePath)) {
            Write-Host "  Skipping $($spec.Name) -- binary missing at $exePath" -ForegroundColor DarkGray
            continue
        }
        $existing = Get-Service -Name $spec.Name -ErrorAction SilentlyContinue
        if (-not $existing) {
            sc.exe create $spec.Name binPath= "`"$exePath`"" start= delayed-auto obj= $spec.Account | Out-Null
            sc.exe description $spec.Name $spec.Desc | Out-Null
            sc.exe failure $spec.Name reset= 3600 actions= restart/5000/restart/30000/restart/60000 | Out-Null
            sc.exe failureflag $spec.Name 1 | Out-Null
            if ($spec.Depends) { sc.exe config $spec.Name depend= $spec.Depends | Out-Null }
            Write-Host "  Re-registered $($spec.Name)" -ForegroundColor Green
        }
    }

    # Restart services (Core -> Broker -> Watchdog)
    foreach ($svcName in @('SuavoAgent.Core', 'SuavoAgent.Broker', 'SuavoAgent.Watchdog')) {
        $svc = Get-Service -Name $svcName -ErrorAction SilentlyContinue
        if (-not $svc) { continue }
        try { Start-Service -Name $svcName -ErrorAction Stop } catch { }
        Write-Host "  $svcName status after repair: $((Get-Service $svcName -ErrorAction SilentlyContinue).Status)" -ForegroundColor Gray
    }

    try { Stop-Transcript -ErrorAction SilentlyContinue | Out-Null } catch { }
    Write-Host ""
    Write-Host "  --repair completed" -ForegroundColor Green
    exit 0
}

Invoke-LegacyNodeAgentQuarantine

$previousAgentConfig = Read-ExistingAgentConfig

if (Test-PriorInstall) {
    Invoke-PriorInstallCleanup
}

function Resolve-ReleaseTag {
    param(
        [string]$TagOrEmpty,
        [string]$Owner,
        [string]$Repo
    )
    if (-not [string]::IsNullOrWhiteSpace($TagOrEmpty)) {
        if ($TagOrEmpty -notmatch '^v\d+\.\d+\.\d+') {
            throw "Invalid release tag format: $TagOrEmpty"
        }
        Write-Host "  Pinned release: $TagOrEmpty" -ForegroundColor DarkGray
        return $TagOrEmpty
    }

    # Fetch latest release metadata. API returns { tag_name: "v3.10.5", ... }.
    $apiUrl = "https://api.github.com/repos/$Owner/$Repo/releases/latest"
    Write-Host "  Resolving latest release from $apiUrl" -ForegroundColor DarkGray
    try {
        $meta = Invoke-RestMethod -Uri $apiUrl -UserAgent "SuavoAgent-Bootstrap" -TimeoutSec 30
    } catch {
        throw "Failed to fetch latest release metadata: $($_.Exception.Message)"
    }

    $tag = $meta.tag_name
    if (-not $tag -or $tag -notmatch '^v\d+\.\d+\.\d+') {
        throw "GitHub returned unexpected tag: '$tag'"
    }
    Write-Host "  Auto-resolved latest release: $tag" -ForegroundColor Green
    return $tag
}

try {
    $ReleaseTag = Resolve-ReleaseTag -TagOrEmpty $ReleaseTag -Owner $RepoOwner -Repo $RepoName
} catch {
    Write-Host "  [FAIL] Release resolution failed: $($_.Exception.Message)" -ForegroundColor Red
    Send-InstallTelemetry -Stage "release_resolve" -Level "fatal" -Message "Release resolution failed: $($_.Exception.Message)" -ExitCode 1
    exit 1
}
$base = "https://github.com/$RepoOwner/$RepoName/releases/download/$ReleaseTag"
$downloadCacheRoot = Join-Path $dataDir "download-cache"
$releaseCacheDir = Join-Path $downloadCacheRoot $ReleaseTag

function Write-Step($msg) {
    $script:CurrentInstallStage = Normalize-InstallTelemetryStage -StageText $msg
    Write-Host "`n[$((Get-Date).ToString('HH:mm:ss'))] $msg" -ForegroundColor Cyan
}
function Write-Ok($msg) { Write-Host "  [OK] $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "  [WARN] $msg" -ForegroundColor Yellow }
function Write-Fail($msg) { Write-Host "  [FAIL] $msg" -ForegroundColor Red }

$installTokenPlain = ConvertTo-PlainTextSecret $InstallToken
$hasProvidedInstallToken = -not [string]::IsNullOrWhiteSpace($installTokenPlain)

if ($previousAgentConfig -and -not $hasProvidedInstallToken) {
    if (-not $ApiKey -and $previousAgentConfig.ApiKey) {
        $ApiKey = [string]$previousAgentConfig.ApiKey
    }
    if (-not $PharmacyId -and $previousAgentConfig.PharmacyId) {
        $PharmacyId = [string]$previousAgentConfig.PharmacyId
    }
    if (-not $AgentId -and $previousAgentConfig.AgentId) {
        $AgentId = [string]$previousAgentConfig.AgentId
    }
    if ($ApiKey -and $PharmacyId -and $AgentId) {
        Write-Ok "Reusing existing cloud registration for agent $AgentId"
    }
} elseif ($previousAgentConfig -and $hasProvidedInstallToken) {
    Write-Ok "Fresh install token provided; existing cloud registration will be replaced"
}

# -- Learning mode is never enabled by installer prompt. It is a post-install
# audited config flip because observing PioneerRx can touch PHI-rendering UI.
if ($PSBoundParameters.ContainsKey('LearningMode') -and [bool]$LearningMode) {
    Write-Warn "Learning mode requested at install time. Confirm BAA/addendum is signed before proceeding."
}

Write-Host ""
Write-Host "  +=======================================+" -ForegroundColor Cyan
Write-Host "  |   SuavoAgent v3 -- Zero-Config Setup   |" -ForegroundColor Cyan
Write-Host "  +=======================================+" -ForegroundColor Cyan
Write-Host ""

# ============================================
# TERMS OF SERVICE + EMPLOYEE MONITORING CONSENT
# ============================================
# This consent is recorded digitally and uploaded to the Suavo cloud
# on first heartbeat. No separate paperwork needed.

# Cache check -- if a recent consent receipt already exists for THIS
# machine AND the SAME OS user that originally accepted it, reuse it and
# skip the prompts. Trip A 2026-04-25 had Nadim re-type consent four
# times across re-installs; the cleanup path now preserves
# consent-receipt.json so subsequent runs find it here.
#
# Codex flagged identity binding on PR #23 review: a machine-only check
# would let a different OS user (e.g. a tech who later RDPs into the same
# pharmacy box) skip consent under the original authorizing party's
# name. Bind reuse to {machineFingerprint, originatingUser} so an OS-user
# change forces a fresh consent prompt.
$cachedConsent = $null
$cachedConsentPath = Join-Path $dataDir "consent-receipt.json"
$currentOsUser = "$env:USERDOMAIN\$env:USERNAME"
if ((-not $SkipConsent) -and (Test-Path $cachedConsentPath)) {
    try {
        $rawCached = Get-Content $cachedConsentPath -Raw -ErrorAction Stop
        $cached = $rawCached | ConvertFrom-Json -ErrorAction Stop
        $currentFingerprint = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Cryptography').MachineGuid
        $cachedTimestamp = $null
        try { $cachedTimestamp = [DateTime]::Parse($cached.consentTimestamp) } catch { }
        $consentAgeDays = if ($cachedTimestamp) { ((Get-Date) - $cachedTimestamp).TotalDays } else { 9999 }
        $sameMachine = $cached.machineFingerprint -eq $currentFingerprint
        # originatingUser may be missing on receipts written by a bootstrap
        # that pre-dates this commit. Treat that as "no binding recorded" and
        # require a fresh prompt so the new binding gets written, rather than
        # letting older receipts silently bypass the OS-user check.
        $sameOsUser = $cached.PSObject.Properties.Match('originatingUser').Count -gt 0 -and `
                      $cached.originatingUser -eq $currentOsUser
        $termsOk = $cached.termsAccepted -eq $true
        if ($sameMachine -and $sameOsUser -and $termsOk -and ($consentAgeDays -lt 90)) {
            $cachedConsent = $cached
            $ageDisplay = [math]::Round($consentAgeDays, 1)
            Write-Host ""
            Write-Ok "Reusing existing consent for this machine ($($cached.authorizingParty.name), recorded $ageDisplay days ago)"
            Write-Host "  To force a fresh consent prompt: del `"$cachedConsentPath`" before re-running" -ForegroundColor DarkGray
        }
    } catch {
        Write-Host "  Could not read cached consent ($($_.Exception.Message)) -- will re-prompt" -ForegroundColor DarkGray
    }
}

# 2026-05-03: install-context pre-fill. When the dashboard provides an
# install token, fetch operational metadata + skip-prompt list from the
# cloud so we can pre-fill ceremony prompts (pharmacist confirms instead
# of types) and skip them entirely for sandbox installs.
$installContext = $null
if ($InstallToken -and -not $cachedConsent) {
    try {
        $tokenForCtx = if ($InstallToken -is [System.Security.SecureString]) {
            $bstr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($InstallToken)
            try { [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($bstr) }
            finally { [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }
        } else { [string]$InstallToken }
        $ctxUri = "$CloudUrl/api/agent/install-context?t=$tokenForCtx"
        $ctxResp = Invoke-RestMethod -Uri $ctxUri -Method Get -TimeoutSec 10 -UseBasicParsing -ErrorAction Stop
        if ($ctxResp.success -and $ctxResp.data) {
            $installContext = $ctxResp.data
            Write-Host ""
            Write-Host "  Pre-filled install context from $($installContext.pharmacy.name)" -ForegroundColor DarkGray
        }
    } catch {
        Write-Host "  Install-context pre-fill unavailable ($($_.Exception.Message)) -- proceeding with full prompts" -ForegroundColor DarkGray
    }
}

# 2026-05-03: SandboxBypass auto-consent. When the cloud's quick-install
# endpoint detects the token's pharmacy is_internal_sandbox=true it appends
# -SandboxBypass. For sandbox installs we skip the operator/state/agreement
# prompts and write a sandbox-tagged consent receipt automatically. The
# HIPAA acknowledgment + agreement-signing requirements don't apply because
# the sandbox pharmacy has no PHI flowing.
if ($SandboxBypass -and -not $cachedConsent) {
    Write-Host ""
    Write-Host "  +======================================================+" -ForegroundColor Cyan
    Write-Host "  |     SUAVOAGENT SANDBOX BYPASS (NON-PHI)             |" -ForegroundColor Cyan
    Write-Host "  +======================================================+" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  This is an MKM-internal sandbox install. Operator pre-filled" -ForegroundColor White
    Write-Host "  as MKM Internal. No patient data flows; HIPAA prompts skipped." -ForegroundColor White
    Write-Host ""
    $authName = if ($installContext -and $installContext.defaults.operator_name) { $installContext.defaults.operator_name } else { "MKM Internal" }
    $authTitle = if ($installContext -and $installContext.defaults.operator_role) { $installContext.defaults.operator_role } else { "MKM Engineer" }
    $confirmState = if ($installContext -and $installContext.pharmacy.state) { $installContext.pharmacy.state } else { "CA" }
    $consentTimestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ss.fffZ")
    $consentReceipt = @{
        installerVersion = $installerVersion
        authorizingParty = @{ name = $authName; title = $authTitle }
        businessState = $confirmState
        consentTimestamp = $consentTimestamp
        sandboxBypass = $true
        machine = $env:COMPUTERNAME
        osUser = $env:USERNAME
        terms = "sandbox-bypass-2026-05-03"
    }
    try {
        if (-not (Test-Path $dataDir)) { New-Item -ItemType Directory -Path $dataDir -Force | Out-Null }
        $consentReceipt | ConvertTo-Json -Depth 5 | Set-Content -Path $cachedConsentPath -Encoding UTF8
        Write-Ok "Sandbox consent receipt recorded ($authName / $env:COMPUTERNAME)"
    } catch {
        Write-Host "  Could not persist sandbox consent receipt ($($_.Exception.Message)) -- continuing" -ForegroundColor DarkGray
    }
} elseif ((-not $SkipConsent) -and (-not $cachedConsent)) {
Write-Host ""
Write-Host "  +======================================================+" -ForegroundColor Cyan
Write-Host "  |         SUAVOAGENT TERMS & CONSENT                  |" -ForegroundColor Cyan
Write-Host "  +======================================================+" -ForegroundColor Cyan
Write-Host ""
Write-Host "  SuavoAgent is workplace monitoring software that observes" -ForegroundColor White
Write-Host "  business workstation activity to optimize delivery operations." -ForegroundColor White
Write-Host ""
Write-Host "  WHAT IT COLLECTS:" -ForegroundColor Yellow
Write-Host "    - Application usage patterns and durations" -ForegroundColor Gray
Write-Host "    - Workstation hardware profile" -ForegroundColor Gray
Write-Host "    - Login/logout timing (shift patterns)" -ForegroundColor Gray
Write-Host "    - Website domain categories (NOT specific URLs)" -ForegroundColor Gray
Write-Host "    - Print event counts (NOT document content)" -ForegroundColor Gray
Write-Host ""
Write-Host "  WHAT IT NEVER COLLECTS:" -ForegroundColor Green
Write-Host "    - Keystrokes, passwords, or typed text" -ForegroundColor Gray
Write-Host "    - Screen captures or screenshots" -ForegroundColor Gray
Write-Host "    - Email, message, or chat content" -ForegroundColor Gray
Write-Host "    - Personal browsing history or specific URLs" -ForegroundColor Gray
Write-Host "    - File contents or document data" -ForegroundColor Gray
Write-Host ""
Write-Host "  LEGAL REQUIREMENTS:" -ForegroundColor Red
Write-Host "    CT, DE, NY: Written notice to each employee REQUIRED by law" -ForegroundColor Red
Write-Host "    CA: CCPA notice at collection required" -ForegroundColor Red
Write-Host "    All states: Employee notification is recommended best practice" -ForegroundColor Yellow
Write-Host ""
Write-Host "  BY PROCEEDING, THE AUTHORIZING PARTY CONFIRMS:" -ForegroundColor Yellow
Write-Host "    1. Authorization to install monitoring software on this machine" -ForegroundColor White
Write-Host "    2. Responsibility to notify all employees per applicable state laws" -ForegroundColor White
Write-Host "    3. Agreement to Suavo's Terms of Service and Privacy Policy" -ForegroundColor White
Write-Host "    4. Execution of Business Associate Agreement (if healthcare)" -ForegroundColor White
Write-Host ""

# Collect authorizing party info -- this gets recorded in the consent receipt.
# 2026-05-03: when install-context is available, pre-fill the prompts so the
# pharmacist confirms with [Enter] instead of typing. Default values come
# from prior pharmacy onboarding (PIC name, license state, etc).
$ctxOperatorName = if ($installContext -and $installContext.defaults.operator_name) { $installContext.defaults.operator_name } else { $null }
$ctxOperatorRole = if ($installContext -and $installContext.defaults.operator_role) { $installContext.defaults.operator_role } else { $null }
$ctxState = if ($installContext -and $installContext.pharmacy.license_state) { $installContext.pharmacy.license_state } else { $null }

$authPrompt = if ($ctxOperatorName) { "  Authorizing party full name [$ctxOperatorName]" } else { "  Authorizing party full name" }
$authName = Read-Host $authPrompt
if ([string]::IsNullOrWhiteSpace($authName)) {
    if ($ctxOperatorName) { $authName = $ctxOperatorName }
    else {
        Write-Host "  Installation cancelled -- authorizing party name required." -ForegroundColor Red
        exit 0
    }
}

$titlePrompt = if ($ctxOperatorRole) { "  Title [$ctxOperatorRole]" } else { "  Title (e.g., Owner, Pharmacy Manager)" }
$authTitle = Read-Host $titlePrompt
if ([string]::IsNullOrWhiteSpace($authTitle)) {
    $authTitle = if ($ctxOperatorRole) { $ctxOperatorRole } else { "Authorized Representative" }
}

$statePrompt = if ($ctxState) { "  State where this business operates [$ctxState]" } else { "  State where this business operates (e.g., CA, NY, TX)" }
$confirmState = Read-Host $statePrompt
if ([string]::IsNullOrWhiteSpace($confirmState)) {
    $confirmState = if ($ctxState) { $ctxState } else { "Unknown" }
}

# Check if mandatory notice state
$mandatoryNoticeStates = @("CT","DE","NY")
$highRiskStates = @("CA","IL","MA","MD","CO","MT")
$stateUpper = $confirmState.ToUpper().Trim()
if ($mandatoryNoticeStates -contains $stateUpper) {
    Write-Host ""
    Write-Host "  *** $stateUpper REQUIRES written employee notice before monitoring ***" -ForegroundColor Red
    Write-Host "  You MUST distribute the employee notice template to all staff" -ForegroundColor Red
    Write-Host "  at this workstation BEFORE SuavoAgent begins collecting data." -ForegroundColor Red
    Write-Host ""
    $noticeConfirm = Read-Host "  Type CONFIRMED to acknowledge this legal requirement"
    if ($noticeConfirm -ne "CONFIRMED") {
        Write-Host "  Installation cancelled -- employee notice acknowledgment required in $stateUpper." -ForegroundColor Red
        exit 0
    }
} elseif ($highRiskStates -contains $stateUpper) {
    Write-Host ""
    Write-Host "  NOTE: $stateUpper has strong privacy protections. Employee notice is" -ForegroundColor Yellow
    Write-Host "  strongly recommended even if not strictly required by statute." -ForegroundColor Yellow
    Write-Host ""
}

Write-Host ""
$finalConfirm = Read-Host "  Type AGREE to accept terms and proceed with installation"
if ($finalConfirm -ne "AGREE") {
    Write-Host "  Installation cancelled." -ForegroundColor Red
    exit 0
}

# Build consent receipt -- saved locally and uploaded on first heartbeat
$consentTimestamp = (Get-Date).ToString("o")
$consentReceipt = @{
    consentVersion = "1.0"
    authorizingParty = @{
        name = $authName
        title = $authTitle
    }
    businessState = $stateUpper
    mandatoryNoticeState = ($mandatoryNoticeStates -contains $stateUpper)
    consentTimestamp = $consentTimestamp
    termsAccepted = $true
    employeeNoticeAcknowledged = ($mandatoryNoticeStates -contains $stateUpper)
    installerVersion = $bootstrapVersion
    machineFingerprint = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Cryptography').MachineGuid
    originatingUser = $currentOsUser
}
Write-Ok "Consent recorded: $authName ($authTitle) at $consentTimestamp"
Write-Host ""
} elseif ($cachedConsent) {
    # Reuse the existing on-disk receipt verbatim. We bump installerVersion
    # to whatever wrote it THIS time so the audit trail still shows when the
    # current bootstrap ran -- but the human acknowledgment + machine
    # binding stay unchanged.
    $authName = $cachedConsent.authorizingParty.name
    $authTitle = $cachedConsent.authorizingParty.title
    $confirmState = $cachedConsent.businessState
    $consentTimestamp = $cachedConsent.consentTimestamp
    $consentReceipt = @{
        consentVersion = $cachedConsent.consentVersion
        authorizingParty = @{ name = $authName; title = $authTitle }
        businessState = $confirmState
        mandatoryNoticeState = $cachedConsent.mandatoryNoticeState
        consentTimestamp = $consentTimestamp
        termsAccepted = $true
        employeeNoticeAcknowledged = $cachedConsent.employeeNoticeAcknowledged
        installerVersion = $bootstrapVersion
        machineFingerprint = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Cryptography').MachineGuid
        # Carry the original binding forward so the next reinstall keeps
        # validating against the same OS user that first accepted.
        originatingUser = $cachedConsent.originatingUser
        source = "cached_reinstall"
    }
} else {
    Write-Ok "Consent recorded via web dashboard -- skipping terminal prompts"
    # Set defaults for the consent receipt (already recorded in cloud)
    $authName = "Web Dashboard"
    $authTitle = "Pre-authorized"
    $confirmState = "WEB"
    $consentTimestamp = (Get-Date).ToString("o")
    $consentReceipt = @{
        consentVersion = "1.0"
        authorizingParty = @{ name = $authName; title = $authTitle }
        businessState = $confirmState
        mandatoryNoticeState = $false
        consentTimestamp = $consentTimestamp
        termsAccepted = $true
        employeeNoticeAcknowledged = $true
        installerVersion = $bootstrapVersion
        machineFingerprint = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Cryptography').MachineGuid
        originatingUser = $currentOsUser
        source = "web_dashboard"
    }
}

# ============================================
# PHASE 1: Detect Pharmacy Management System
# ============================================
Write-Step "Phase 1: Detecting pharmacy management system"

$pmsType = $null
$pioneerDir = $null
$pioneerExe = $null
$pioneerConfig = $null

# --- PioneerRx detection ---
$pioneerPaths = @(
    "C:\Program Files (x86)\New Tech Computer Systems\PioneerRx",
    "C:\Program Files\New Tech Computer Systems\PioneerRx",
    "D:\Program Files (x86)\New Tech Computer Systems\PioneerRx",
    "D:\Program Files\New Tech Computer Systems\PioneerRx"
)
try {
    $regPaths = @(
        "HKLM:\SOFTWARE\WOW6432Node\New Tech Computer Systems",
        "HKLM:\SOFTWARE\New Tech Computer Systems"
    )
    foreach ($rp in $regPaths) {
        if (Test-Path $rp) {
            $regInstall = (Get-ItemProperty $rp -ErrorAction SilentlyContinue).InstallPath
            if ($regInstall) { $pioneerPaths = @($regInstall) + $pioneerPaths }
        }
    }
} catch {}
foreach ($p in $pioneerPaths) {
    # [hotfix] Use IO.Path.Combine (string concat only) instead of Join-Path
    # which validates the drive exists and throws on e.g. "D:\..." when D:
    # isn't mounted. Test-Path handles non-existent drives cleanly (returns
    # $false) so the loop skips missing candidates without dying.
    $exe = [System.IO.Path]::Combine($p, "PioneerPharmacy.exe")
    $cfg = [System.IO.Path]::Combine($p, "PioneerPharmacy.exe.config")
    if ((Test-Path $exe) -and (Test-Path $cfg)) {
        $pioneerDir = $p; $pioneerExe = $exe; $pioneerConfig = $cfg; $pmsType = "PioneerRx"
        break
    }
}
if (-not $pmsType) {
    $proc = Get-Process -Name "PioneerPharmacy" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($proc) {
        $pioneerExe = $proc.Path; $pioneerDir = Split-Path $pioneerExe -Parent
        $pioneerConfig = "$pioneerExe.config"; $pmsType = "PioneerRx"
    }
}

# --- Future PMS detections go here ---
# QS/1: Check for "QS1.exe" or registry
# Liberty: Check for "Liberty.exe" or known paths
# McKesson: Check for "EnterpriseRx" paths
# Each sets $pmsType and relevant config vars

# --- Result ---
# Derive the runtime ProcessNameGlob from the actual exe basename instead of
# hardcoding "PioneerPharmacy*". Future PMS detections set $pioneerExe to
# their own .exe path; this stays correct as new adapters land. Trip A
# 2026-04-25 surfaced the risk: the hardcoded glob worked at Better Life
# only because PioneerRx happens to ship as PioneerPharmacy.exe -- a
# pharmacy with a renamed/repackaged exe would have silently captured zero.
$pmsProcessName = if ($pioneerExe) {
    [System.IO.Path]::GetFileNameWithoutExtension($pioneerExe)
} else {
    # No exe detected -- fall back to the documented PioneerRx default so
    # an agent that boots before its PMS does still has a glob to match.
    "PioneerPharmacy"
}

if ($pmsType) {
    Write-Ok "Detected: $pmsType at $pioneerDir (process: $pmsProcessName)"
} else {
    Write-Warn "No pharmacy management system detected on this machine"
    Write-Host "  The agent will install and auto-discover the PMS during its learning phase." -ForegroundColor Gray
    Write-Host "  Supported: PioneerRx (more adapters coming)" -ForegroundColor Gray
    Write-Host ""
}

# ============================================
# PHASE 2: Extract SQL credentials
# ============================================
# Pause transcript during credential discovery -- SQL passwords must not be logged
try { Stop-Transcript -ErrorAction SilentlyContinue | Out-Null } catch { }

if (-not $pmsType) {
    Write-Step "Phase 2: Skipping SQL discovery (no PMS detected)"
    $sqlServer = ""
    $sqlDatabase = ""
    $sqlUser = $null
    $sqlPassword = $null
    Write-Host "  Agent will discover SQL during learning phase" -ForegroundColor Gray
} elseif ($LearningMode) {
    # Tier 0 (-LearningMode) is UIA-only -- it never queries SQL. Skipping
    # the discovery + manual-credential fallback removes a pharmacist-facing
    # prompt that surfaced four times during Trip A 2026-04-25 (Nadim was
    # asked "Use SQL Auth? (y/n)" then "SQL Username" / "SQL Password" with
    # no way to know the right answers).
    Write-Step "Phase 2: Skipping SQL discovery (-LearningMode is UIA-only)"
    $sqlServer = ""
    $sqlDatabase = ""
    $sqlUser = $null
    $sqlPassword = $null
    Write-Host "  Tier 0 observe-only mode does not access SQL Server" -ForegroundColor Gray
} else {
    Write-Step "Phase 2: Discovering SQL Server credentials"
}

if ($pmsType -and -not $LearningMode) {
	$sqlServer = $null
	$sqlDatabase = "PioneerPharmacySystem"
	$sqlUser = $null
	$sqlPassword = $null
	$reusePreviousSqlSettings = $false

	if ($previousAgentConfig -and $previousAgentConfig.SqlServer) {
	    $sqlServer = [string]$previousAgentConfig.SqlServer
	    if ($previousAgentConfig.SqlDatabase) {
	        $sqlDatabase = [string]$previousAgentConfig.SqlDatabase
	    }
	    if ($previousAgentConfig.SqlUser) {
	        $sqlUser = [string]$previousAgentConfig.SqlUser
	    }
	    if ($previousAgentConfig.SqlPassword) {
	        $sqlPassword = [string]$previousAgentConfig.SqlPassword
	    }
	    $reusePreviousSqlSettings = $true
	    Write-Ok "Reusing previous SQL settings from local appsettings.json"
	}

# Step 2a: Read config for host
$configXml = [xml](Get-Content $pioneerConfig)
$pioneerHost = $null

# Try newTechDataConfiguration element
$ntdc = $configXml.configuration.newTechDataConfiguration
if ($ntdc) {
    $pioneerHost = $ntdc.host
    if (-not $pioneerHost) { $pioneerHost = $ntdc.server }
    if (-not $pioneerHost) { $pioneerHost = $ntdc.GetAttribute("host") }
}

# Fallback: search all attributes for host-like values
if (-not $pioneerHost) {
    $configText = Get-Content $pioneerConfig -Raw
    if ($configText -match 'host\s*=\s*"([^"]+)"') {
        $pioneerHost = $Matches[1]
    } elseif ($configText -match 'server\s*=\s*"([^"]+)"') {
        $pioneerHost = $Matches[1]
    }
}

if ($pioneerHost) {
    Write-Ok "PioneerRx host: $pioneerHost"
} else {
    Write-Warn "Could not extract host from config -- will try localhost"
    $pioneerHost = "localhost"
}

# Step 2b: Load Enterprise Library DLL and call ConnectionStringServer
$entLibDll = Join-Path $pioneerDir "Microsoft.Practices.EnterpriseLibrary.Data.dll"
$discoveredConnStr = $null

if (Test-Path $entLibDll) {
    Write-Host "  Loading Enterprise Library DLL..." -ForegroundColor Gray
    try {
        [System.Reflection.Assembly]::LoadFrom($entLibDll) | Out-Null

        # Find the method -- it may be in different classes depending on version
        $dataTypes = [AppDomain]::CurrentDomain.GetAssemblies() |
            Where-Object { $_.GetName().Name -eq "Microsoft.Practices.EnterpriseLibrary.Data" } |
            ForEach-Object { $_.GetTypes() } |
            Where-Object { $_.GetMethods([System.Reflection.BindingFlags]::Static -bor [System.Reflection.BindingFlags]::Public -bor [System.Reflection.BindingFlags]::NonPublic) |
                Where-Object { $_.Name -like "*ConnectionString*Network*" -or $_.Name -like "*Retrieve*Connection*" } }

        foreach ($type in $dataTypes) {
            $methods = $type.GetMethods([System.Reflection.BindingFlags]::Static -bor [System.Reflection.BindingFlags]::Public -bor [System.Reflection.BindingFlags]::NonPublic) |
                Where-Object { $_.Name -like "*ConnectionString*" -or $_.Name -like "*Retrieve*" }
            foreach ($method in $methods) {
                $params = $method.GetParameters()
                if ($params.Count -ge 2) {
                    $paramSignature = ($params | ForEach-Object { $_.ParameterType.Name }) -join ', '
                    Write-Host "  Found method: $($type.FullName).$($method.Name)($paramSignature)" -ForegroundColor Gray
                    try {
                        if ($params.Count -eq 3) {
                            $discoveredConnStr = $method.Invoke($null, @($sqlDatabase, $pioneerHost, 12345))
                        } elseif ($params.Count -eq 2) {
                            $discoveredConnStr = $method.Invoke($null, @($sqlDatabase, $pioneerHost))
                        }
                        if ($discoveredConnStr) {
                            Write-Ok "ConnectionStringServer returned credentials"
                            break
                        }
                    } catch {
                        Write-Host "    Method call failed: $($_.Exception.InnerException.Message)" -ForegroundColor Gray
                    }
                }
            }
            if ($discoveredConnStr) { break }
        }
    } catch {
        Write-Warn "Enterprise Library DLL load failed: $($_.Exception.Message)"
    }
}

# Step 2c: Try direct TCP to ConnectionStringServer port 12345
if (-not $discoveredConnStr) {
    Write-Host "  Trying direct TCP to ${pioneerHost}:12345..." -ForegroundColor Gray
    try {
        $tcp = New-Object System.Net.Sockets.TcpClient
        $tcp.Connect($pioneerHost, 12345)
        $stream = $tcp.GetStream()
        $stream.ReadTimeout = 5000
        $stream.WriteTimeout = 5000

        # Send database name request (common protocol: length-prefixed UTF-8 string)
        $reqBytes = [System.Text.Encoding]::UTF8.GetBytes($sqlDatabase)
        $lenBytes = [BitConverter]::GetBytes([int32]$reqBytes.Length)
        $stream.Write($lenBytes, 0, 4)
        $stream.Write($reqBytes, 0, $reqBytes.Length)
        $stream.Flush()

        # Read response
        $buf = New-Object byte[] 4096
        $read = $stream.Read($buf, 0, $buf.Length)
        if ($read -gt 0) {
            # Try reading as length-prefixed
            $respStr = [System.Text.Encoding]::UTF8.GetString($buf, 0, $read)
            # Skip length prefix bytes if present
            if ($respStr.Length -gt 4 -and $respStr.Substring(4) -match "Data Source|Server") {
                $discoveredConnStr = $respStr.Substring(4)
            } elseif ($respStr -match "Data Source|Server") {
                $discoveredConnStr = $respStr.TrimStart([char]0, [char]1, [char]2, [char]3, [char]4, [char]5)
            }
            if ($discoveredConnStr) {
                Write-Ok "Got connection string from TCP port 12345"
            }
        }
        $tcp.Close()
    } catch {
        Write-Host "    TCP probe failed: $($_.Exception.Message)" -ForegroundColor Gray
    }
}

# Step 2d: Parse connection string if discovered
if ($discoveredConnStr) {
    Write-Host "  Parsing connection string..." -ForegroundColor Gray
    try {
        $csb = New-Object System.Data.SqlClient.SqlConnectionStringBuilder($discoveredConnStr)
        $sqlServer = $csb.DataSource
        $sqlDatabase = if ($csb.InitialCatalog) { $csb.InitialCatalog } else { $sqlDatabase }
        if (-not $csb.IntegratedSecurity) {
            $sqlUser = $csb.UserID
            $sqlPassword = $csb.Password
        }
        Write-Ok "SQL Server: $sqlServer"
        Write-Ok "Database: $sqlDatabase"
        Write-Ok "Auth: $(if ($sqlUser) { 'SQL Auth as ' + $sqlUser } else { 'Windows Auth' })"
    } catch {
        Write-Warn "Connection string parse failed: $($_.Exception.Message)"
    }
}

# Step 2e: Fallback -- SQL Browser discovery
if (-not $sqlServer) {
    Write-Host "  Trying SQL Browser on $pioneerHost..." -ForegroundColor Gray
    try {
        $udp = New-Object System.Net.Sockets.UdpClient
        $udp.Client.ReceiveTimeout = 3000
        $ep = New-Object System.Net.IPEndPoint([System.Net.IPAddress]::Parse(
            ([System.Net.Dns]::GetHostAddresses($pioneerHost) | Where-Object { $_.AddressFamily -eq 'InterNetwork' } | Select-Object -First 1).IPAddressToString
        ), 1434)
        $udp.Send(@(0x02), 1, $ep) | Out-Null
        $recvEp = New-Object System.Net.IPEndPoint([System.Net.IPAddress]::Any, 0)
        $resp = $udp.Receive([ref]$recvEp)
        $respStr = [System.Text.Encoding]::ASCII.GetString($resp, 3, $resp.Length - 3)
        $udp.Close()

        # Parse "InstanceName;NEWTECH;;tcp;49202;..."
        $parts = $respStr.Split(';')
        $instance = $null; $port = $null
        for ($i = 0; $i -lt $parts.Length - 1; $i++) {
            if ($parts[$i] -eq "InstanceName") { $instance = $parts[$i+1] }
            if ($parts[$i] -eq "tcp" -and $parts[$i+1] -match '^\d+$') { $port = $parts[$i+1] }
        }
        if ($port) {
            $resolvedIp = ([System.Net.Dns]::GetHostAddresses($pioneerHost) |
                Where-Object { $_.AddressFamily -eq 'InterNetwork' } |
                Select-Object -First 1).IPAddressToString
            $sqlServer = "${resolvedIp},${port}"
            Write-Ok "SQL Browser found: $sqlServer (instance: $instance)"
        }
    } catch {
        Write-Host "    SQL Browser failed: $($_.Exception.Message)" -ForegroundColor Gray
    }
}

# Step 2f: If we still have no credentials, prompt
if (-not $sqlServer) {
    Write-Warn "Auto-discovery failed. Manual entry required."
    $sqlServer = Read-Host "  SQL Server (e.g. 192.168.1.78,49202)"
}
if (-not $reusePreviousSqlSettings -and -not $sqlUser -and -not $discoveredConnStr) {
    Write-Warn "No SQL credentials discovered."
    $needAuth = Read-Host "  Use SQL Auth? (y/n)"
    if ($needAuth -eq 'y') {
        $sqlUser = Read-Host "  SQL Username"
        $sqlPassword = Read-Host "  SQL Password"
    }
}
} # end if ($pmsType)

# Resume transcript -- credentials are now in variables, not transcript
try { Start-Transcript -Path $transcriptPath -Append -ErrorAction SilentlyContinue | Out-Null } catch { }

Write-Host ""
if ($pmsType) {
    Write-Host "  +-------------------------------------+" -ForegroundColor White
    Write-Host "  | Server:   $sqlServer" -ForegroundColor White
    Write-Host "  | Database: $sqlDatabase" -ForegroundColor White
    Write-Host "  | Auth:     $(if ($sqlUser) { "SQL ($sqlUser)" } else { 'Windows' })" -ForegroundColor White
    Write-Host "  +-------------------------------------+" -ForegroundColor White
} else {
    Write-Host "  +-------------------------------------+" -ForegroundColor White
    Write-Host "  | SQL discovery deferred to agent     |" -ForegroundColor Gray
    Write-Host "  | (no PMS detected on this machine)   |" -ForegroundColor Gray
    Write-Host "  +-------------------------------------+" -ForegroundColor White
}

# ============================================
# PHASE 3: Download agent binaries
# ============================================
Write-Step "Phase 3: Downloading SuavoAgent binaries"

New-Item -ItemType Directory -Path $installDir -Force | Out-Null
New-Item -ItemType Directory -Path "$dataDir\logs" -Force | Out-Null
$downloadCacheAvailable = $true
try {
    New-Item -ItemType Directory -Path $releaseCacheDir -Force | Out-Null
} catch {
    $downloadCacheAvailable = $false
    Write-Warn "Binary download cache unavailable: $($_.Exception.Message)"
}

# HIPAA 164.312(a)(2)(iv) -- lock down data dir to SYSTEM + LocalService +
# NetworkService (Broker) + Administrators + INTERACTIVE (Helper, Phase 5.6).
# Runtime service account lacks WRITE_DAC so this is the one-and-only place
# the DACL gets pinned.
#
# INTERACTIVE (S-1-5-4) is added because Phase 5.6 now spawns Helper into the
# logged-in user's session via CreateProcessAsUser. Helper needs Modify to
# read state.db / state.key / vision.json / pioneerrx.json and to write
# helper-*.log entries. INTERACTIVE only applies to currently-logged-in
# console users -- services in Session 0 still hit their explicit rules
# above, preserving the HIPAA threat model. Pre-3.14.1 installs lacked this
# rule, which crashed Helper at startup with .NET Event 1023 "Failed to
# resolve full path of the current executable" (verified Queen 2026-05-05).
try {
    $dataAcl = Get-Acl $dataDir
    $dataAcl.SetAccessRuleProtection($true, $false) # strip inherited rules
    $rules = @(
        (New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\SYSTEM", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")),
        (New-Object System.Security.AccessControl.FileSystemAccessRule(
            "BUILTIN\Administrators", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")),
        (New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\LOCAL SERVICE", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")),
        (New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\NETWORK SERVICE", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow")),
        (New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\INTERACTIVE", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow"))
    )
    foreach ($rule in $rules) { $dataAcl.AddAccessRule($rule) }
    Set-Acl $dataDir $dataAcl
    Write-Ok "Data dir ACL locked down ($dataDir)"
} catch {
    Write-Fail "Failed to lock data dir ACL: $($_.Exception.Message)"
    Send-InstallTelemetry -Stage "data_acl" -Level "fatal" -Message "Failed to lock data dir ACL: $($_.Exception.Message)" -ExitCode 1
    throw
}

# Download and verify checksums
$checksumUrl = "$base/checksums.sha256"
$checksumSigUrl = "$base/checksums.sha256.sig"
$checksumPath = Join-Path $installDir "checksums.sha256"
$checksumSigPath = Join-Path $installDir "checksums.sha256.sig"

Write-Host "  Downloading checksums..." -ForegroundColor Gray
try {
    Invoke-WebRequest -Uri $checksumUrl -OutFile $checksumPath -UseBasicParsing
    Invoke-WebRequest -Uri $checksumSigUrl -OutFile $checksumSigPath -UseBasicParsing
} catch {
    Write-Fail "Checksum download failed: $($_.Exception.Message)"
    Send-InstallTelemetry -Stage "checksum_download" -Level "fatal" -Message "Checksum download failed: $($_.Exception.Message)" -ExitCode 1
    exit 1
}

# Verify ECDSA signature of checksums using only .NET Framework 4.6.0-
# compatible primitives -- PowerShell 5.1 ships with .NET Framework 4.6.x
# on many pharmacy Windows installs, and several newer APIs crash there:
#   * ImportSubjectPublicKeyInfo          -> .NET 5+ only
#   * [Convert]::FromHexString            -> .NET 5+ only
#   * ECCurve.NamedCurves.nistP256        -> .NET Framework 4.7.2+
#   * VerifyData(bytes,bytes,HashAlgName) -> .NET Framework 4.6.1+, flaky on 4.6
#   * ECDsaCng.VerifyData(DER signature)  -> expects IEEE P1363 raw r||s
# openssl dgst -sign emits binary DER, so we also must parse DER ourselves.
#
# Strategy: build a BCRYPT_ECCKEY_BLOB (available since .NET 3.5 via CngKey.Import),
# hand-convert the DER sig to P1363, and verify a pre-computed SHA-256 hash.

$publicKeyDer = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBLRvZ572EpqNab9CxJ9/b/GfHpHOrhWkpaaCzIkXQ5d2dwiqdJHlxvrgN0/zCsgp/ccnDXed4DFCkh6wUWCvWA=="
$derBytes = [System.Convert]::FromBase64String($publicKeyDer)
if ($derBytes.Length -lt 65 -or $derBytes[$derBytes.Length - 65] -ne 0x04) {
    Write-Fail "Embedded public key is not a valid P-256 uncompressed point"
    Send-InstallTelemetry -Stage "signature_verify" -Level "fatal" -Message "Embedded public key is not a valid P-256 uncompressed point" -ExitCode 1
    exit 1
}
$qx = New-Object byte[] 32
$qy = New-Object byte[] 32
[Array]::Copy($derBytes, $derBytes.Length - 64, $qx, 0, 32)
[Array]::Copy($derBytes, $derBytes.Length - 32, $qy, 0, 32)

# BCRYPT_ECCKEY_BLOB layout for a P-256 public key (72 bytes total):
#   dwMagic : uint32 LE = 0x31534345 (BCRYPT_ECDSA_PUBLIC_P256_MAGIC, "ECS1")
#   cbKey   : uint32 LE = 32 (size of each coordinate for P-256)
#   X[32], Y[32]
$blob = New-Object byte[] 72
$blob[0] = 0x45; $blob[1] = 0x43; $blob[2] = 0x53; $blob[3] = 0x31  # "ECS1" LE
$blob[4] = 0x20; $blob[5] = 0x00; $blob[6] = 0x00; $blob[7] = 0x00  # cbKey=32 LE
[Array]::Copy($qx, 0, $blob, 8, 32)
[Array]::Copy($qy, 0, $blob, 40, 32)

$cngKey = [System.Security.Cryptography.CngKey]::Import(
    $blob,
    [System.Security.Cryptography.CngKeyBlobFormat]::EccPublicBlob)
$ecdsa = New-Object System.Security.Cryptography.ECDsaCng($cngKey)

$checksumBytes = [System.IO.File]::ReadAllBytes($checksumPath)
$sigBytes      = [System.IO.File]::ReadAllBytes($checksumSigPath)

# Convert DER ECDSA signature to IEEE P1363 (raw r||s, 64 bytes for P-256).
# DER layout: 30 <seqLen> 02 <rLen> <r-bytes> 02 <sLen> <s-bytes>
# r/s each may carry a leading 0x00 sign-bit padding byte from DER encoding.
if ($sigBytes.Length -lt 8 -or $sigBytes[0] -ne 0x30) {
    Write-Fail "Signature is not a valid DER SEQUENCE"
    Send-InstallTelemetry -Stage "signature_verify" -Level "fatal" -Message "Signature is not a valid DER SEQUENCE" -ExitCode 1
    exit 1
}
$seqHdrLen = 2
if (($sigBytes[1] -band 0x80) -ne 0) {
    $seqHdrLen = 2 + ($sigBytes[1] -band 0x7F)
}
if ($sigBytes[$seqHdrLen] -ne 0x02) {
    Write-Fail "Signature missing r INTEGER tag"
    Send-InstallTelemetry -Stage "signature_verify" -Level "fatal" -Message "Signature missing r INTEGER tag" -ExitCode 1
    exit 1
}
$rLenOrig = [int]$sigBytes[$seqHdrLen + 1]
$rStart   = $seqHdrLen + 2
$rEnd     = $rStart + $rLenOrig

if ($sigBytes[$rEnd] -ne 0x02) {
    Write-Fail "Signature missing s INTEGER tag"
    Send-InstallTelemetry -Stage "signature_verify" -Level "fatal" -Message "Signature missing s INTEGER tag" -ExitCode 1
    exit 1
}
$sLenOrig = [int]$sigBytes[$rEnd + 1]
$sStart   = $rEnd + 2
$sEnd     = $sStart + $sLenOrig

if ($sEnd -ne $sigBytes.Length) {
    Write-Fail "Signature DER length mismatch (expected $($sigBytes.Length), got $sEnd)"
    Send-InstallTelemetry -Stage "signature_verify" -Level "fatal" -Message "Signature DER length mismatch" -ExitCode 1
    exit 1
}

$rLen = $rLenOrig
while ($rLen -gt 0 -and $sigBytes[$rStart] -eq 0) { $rStart++; $rLen-- }
$sLen = $sLenOrig
while ($sLen -gt 0 -and $sigBytes[$sStart] -eq 0) { $sStart++; $sLen-- }
if ($rLen -gt 32 -or $sLen -gt 32) {
    Write-Fail "Signature r or s exceeds 32 bytes after stripping padding"
    Send-InstallTelemetry -Stage "signature_verify" -Level "fatal" -Message "Signature r or s exceeds 32 bytes after stripping padding" -ExitCode 1
    exit 1
}

$p1363 = New-Object byte[] 64
[Array]::Copy($sigBytes, $rStart, $p1363, 32 - $rLen, $rLen)
[Array]::Copy($sigBytes, $sStart, $p1363, 64 - $sLen, $sLen)

# VerifyHash is the most portable path -- avoids HashAlgorithmName overload
# differences between 4.6.x point releases.
$sha256 = [System.Security.Cryptography.SHA256]::Create()
$hash   = $sha256.ComputeHash($checksumBytes)
$valid  = $ecdsa.VerifyHash($hash, $p1363)

if (-not $valid) {
    Write-Fail "CRITICAL: Checksum signature verification FAILED - aborting install"
    Send-InstallTelemetry -Stage "signature_verify" -Level "fatal" -Message "Checksum signature verification failed" -ExitCode 1
    Remove-Item $checksumPath, $checksumSigPath -Force -ErrorAction SilentlyContinue
    exit 1
}
Write-Host "  Checksum signature verified (ECDSA P-256)" -ForegroundColor Green

# Parse expected hashes
$expectedHashes = @{}
Get-Content $checksumPath | ForEach-Object {
    $parts = $_ -split "  ", 2
    if ($parts.Count -eq 2) { $expectedHashes[$parts[1].Trim()] = $parts[0].Trim() }
}

$binaries = @("SuavoAgent.Core.exe", "SuavoAgent.Broker.exe", "SuavoAgent.Helper.exe", "SuavoAgent.Watchdog.exe")

# Verify ALL expected binaries have checksum entries before downloading anything
foreach ($bin in $binaries) {
    if (-not $expectedHashes.ContainsKey($bin)) {
        Write-Fail "CRITICAL: Checksum missing for $bin -- aborting install"
        Send-InstallTelemetry -Stage "signature_verify" -Level "fatal" -Message "Checksum missing for $bin" -ExitCode 1
        exit 1
    }
}

function Test-VerifiedCachedBinary {
    param(
        [string]$cachedPath,
        [string]$ExpectedHash
    )

    if (-not (Test-Path $cachedPath -PathType Leaf)) {
        return $null
    }

    try {
        $cachedHash = (Get-FileHash -Path $cachedPath -Algorithm SHA256).Hash.ToLower()
        if ($cachedHash -eq $ExpectedHash) {
            return $cachedPath
        }
        Write-Warn "Cached $(Split-Path $cachedPath -Leaf) failed hash check; re-downloading"
    } catch {
        Write-Warn "Could not verify cached $(Split-Path $cachedPath -Leaf): $($_.Exception.Message)"
    }

    Remove-Item -Path $cachedPath -Force -ErrorAction SilentlyContinue
    return $null
}

foreach ($bin in $binaries) {
    $url = "$base/$bin"
    $dst = Join-Path $installDir $bin
    $expectedHash = $expectedHashes[$bin]
    $cachedBinary = $null
    $reusedFromCache = $false

    if ($downloadCacheAvailable) {
        $cachedPath = Join-Path $releaseCacheDir $bin
        $cachedBinary = Test-VerifiedCachedBinary -cachedPath $cachedPath -ExpectedHash $expectedHash
    }

    if ($cachedBinary) {
        Write-Host "  Reusing cached $bin..." -ForegroundColor Gray
        try {
            Copy-Item -Path $cachedBinary -Destination $dst -Force
            $sizeMb = [math]::Round((Get-Item $dst).Length / 1MB, 1)
            Write-Ok "$bin ($sizeMb MB, cached)"
            $reusedFromCache = $true
        } catch {
            Write-Warn "Cached copy failed for ${bin}: $($_.Exception.Message); downloading fresh"
            Remove-Item -Path $dst -Force -ErrorAction SilentlyContinue
        }
    }

    if (-not $reusedFromCache) {
        Write-Host "  Downloading $bin..." -ForegroundColor Gray
        try {
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
            Invoke-WebRequest -Uri $url -OutFile $dst -UseBasicParsing
            $sizeMb = [math]::Round((Get-Item $dst).Length / 1MB, 1)
            Write-Ok "$bin ($sizeMb MB)"
        } catch {
            Write-Fail "Download failed for $bin -- $($_.Exception.Message)"
            Send-InstallTelemetry -Stage "download_binary" -Level "fatal" -Message "Download failed for $bin -- $($_.Exception.Message)" -ExitCode 1
            exit 1
        }
    }

    # Verify SHA256 hash against signed checksums
    $actualHash = (Get-FileHash -Path $dst -Algorithm SHA256).Hash.ToLower()
    if ($actualHash -ne $expectedHash) {
        Write-Fail "CRITICAL: SHA256 mismatch for $bin - expected $expectedHash, got $actualHash"
        Send-InstallTelemetry -Stage "download_hash" -Level "fatal" -Message "SHA256 mismatch for $bin" -ExitCode 1
        if ($cachedBinary) { Remove-Item -Path $cachedBinary -Force -ErrorAction SilentlyContinue }
        foreach ($b in $binaries) { Remove-Item (Join-Path $installDir $b) -Force -ErrorAction SilentlyContinue }
        exit 1
    }
    Write-Host "  $bin verified: $actualHash" -ForegroundColor Green

    if ($downloadCacheAvailable -and -not $reusedFromCache) {
        $cacheDst = Join-Path $releaseCacheDir $bin
        try {
            Copy-Item -Path $dst -Destination $cacheDst -Force
        } catch {
            Write-Warn "Could not update binary cache for ${bin}: $($_.Exception.Message)"
        }
    }
}

# ============================================
# SECURITY CHECK: BitLocker Status
# ============================================
Write-Step "Security: Checking disk encryption"
$bitlockerStatus = $null
try {
    $bitlockerStatus = (manage-bde -status $env:SystemDrive 2>$null | Select-String "Protection Status").ToString()
} catch { }

if ($bitlockerStatus -and $bitlockerStatus -match "Protection On") {
    Write-Ok "BitLocker is ENABLED on $env:SystemDrive -- HIPAA breach safe harbor active"
} else {
    Write-Warn "BitLocker is NOT enabled on $env:SystemDrive"
    Write-Host "  HIPAA RECOMMENDATION: Enable BitLocker for full-disk encryption" -ForegroundColor Yellow
    Write-Host "  Without BitLocker, a stolen computer = reportable HIPAA breach" -ForegroundColor Yellow
    Write-Host "  Delivery receipts are encrypted by SuavoAgent (DPAPI) regardless" -ForegroundColor Gray
    Write-Host ""
}

# ============================================
# PHASE 4: Write appsettings.json
# ============================================
Write-Step "Phase 4: Writing configuration"

$fingerprint = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Cryptography').MachineGuid

# -- Register with cloud via install token (dashboard onboarding path) --
if (-not $InstallToken -and -not $ApiKey) {
    Write-Step "Install token required for cloud registration"
    $InstallToken = Read-Host "Paste one-time Suavo install token" -AsSecureString
    $installTokenPlain = ConvertTo-PlainTextSecret $InstallToken
}

if ($installTokenPlain) {
    $script:InstallTelemetryToken = $installTokenPlain
    Write-Step "Registering agent with cloud using install token..."
    try {
        $machineName = [System.Net.Dns]::GetHostName()
        $registerBody = @{
            licenseKey = "0000000000"  # Token flow ignores NPI; server validates /^\d{10}$/, so use the documented placeholder
            installToken = $installTokenPlain
            machineName = $machineName
            machineFingerprint = $fingerprint
            agentVersion = $ReleaseTag.TrimStart('v')
        } | ConvertTo-Json -Depth 3
        $registerResp = Invoke-RestMethod `
            -Uri "$CloudUrl/api/agent/register" `
            -Method POST `
            -ContentType "application/json" `
            -Body $registerBody `
            -TimeoutSec 30
        if (-not $registerResp.success) {
            throw "Cloud rejected registration: $($registerResp.error)"
        }
        $ApiKey = $registerResp.data.apiKey
        $AgentId = $registerResp.data.agentId
        $PharmacyId = $registerResp.data.pharmacyId
        if (-not $AgentId) {
            throw "Cloud registration did not return agentId"
        }
        Write-Ok "Registered agent $AgentId for pharmacy $PharmacyId"

        # Eager bootstrap of cloud config overrides BEFORE Core starts.
        # ConfigSyncWorker still runs the steady-state poll loop after boot,
        # but writing the file pre-boot guarantees IOptions consumers see
        # the right values on FIRST construction (no restart-after-poll
        # ceremony required, no race window where Core boots with stale config).
        try {
            $initialOverrides = $registerResp.data.initialOverrides
            if ($initialOverrides -and ($initialOverrides | Measure-Object).Count -gt 0) {
                $root = @{}
                foreach ($ov in $initialOverrides) {
                    if (-not $ov.path) { continue }
                    $segments = $ov.path -split '\.'
                    $node = $root
                    for ($i = 0; $i -lt $segments.Length - 1; $i++) {
                        $seg = $segments[$i]
                        if (-not $node.ContainsKey($seg) -or -not ($node[$seg] -is [hashtable])) {
                            $node[$seg] = @{}
                        }
                        $node = $node[$seg]
                    }
                    $node[$segments[-1]] = $ov.value
                }
                $overridesJson = $root | ConvertTo-Json -Depth 10 -Compress:$false
                $overridesPath = Join-Path $dataDir "config-overrides.json"
                if (-not (Test-Path $dataDir)) { New-Item -ItemType Directory -Path $dataDir -Force | Out-Null }
                $tmpPath = "$overridesPath.tmp"
                Set-Content -Path $tmpPath -Value $overridesJson -Encoding UTF8 -NoNewline
                Move-Item -Path $tmpPath -Destination $overridesPath -Force
                Write-Ok "Initial config overrides written: $($initialOverrides.Count) key(s) to config-overrides.json"
            } else {
                Write-Host "    No initial overrides for this agent (cloud has none configured yet)" -ForegroundColor DarkGray
            }
        } catch {
            Write-Host "    Initial overrides write skipped: $($_.Exception.Message)" -ForegroundColor DarkGray
            Write-Host "    Non-fatal -- ConfigSyncWorker will fetch on first poll instead" -ForegroundColor DarkGray
        }
    } catch {
        Write-Fail "Registration failed: $($_.Exception.Message)"
        Send-InstallTelemetry -Stage "cloud_register" -Level "fatal" -Message "Registration failed: $($_.Exception.Message)" -ExitCode 1
        exit 1
    } finally {
        $installTokenPlain = $null
        $InstallToken = $null
    }
}

if (-not $ApiKey -or -not $AgentId -or -not $PharmacyId) {
    Write-Fail "Cloud registration is required but did not produce a complete agent identity"
    Write-Host "  Re-run the one-paste installer with a fresh install token from the Suavo dashboard." -ForegroundColor Yellow
    Write-Host "  Local-only fallback IDs are not allowed for production installs." -ForegroundColor Yellow
    Send-InstallTelemetry -Stage "cloud_register" -Level "fatal" -Message "Cloud registration did not produce ApiKey, AgentId, and PharmacyId" -ExitCode 1
    exit 1
}

$config = @{
    Agent = @{
        CloudUrl = $CloudUrl
        ApiKey = $ApiKey
        AgentId = $AgentId
        PharmacyId = $PharmacyId
        MachineFingerprint = $fingerprint
        Version = $ReleaseTag.TrimStart('v')
        SqlServer = $sqlServer
        SqlDatabase = $sqlDatabase
        SqlTrustServerCertificate = $false
        LearningMode = [bool]$LearningMode
        ReceiptOnlyMode = $true
        TemplateLearning = @{
            Enabled = $false
            Mode = "capture"
            SkillId = "learned"
            ProcessNameGlob = "${pmsProcessName}*"
            RuleGeneration = $false
            AutoApproveOnFingerprintMatch = $false
        }
        AutoExecution = @{
            Enabled = $false
            RequireConfirmation = $true
            WritebackEnabled = $false
        }
        Vision = @{
            Enabled = $false
        }
        FleetFeatures = @{
            SchemaAdaptation = $false
        }
    }
}
if ($sqlUser) {
    $config.Agent.SqlUser = $sqlUser
    $config.Agent.SqlPassword = $sqlPassword
}

$configJson = $config | ConvertTo-Json -Depth 5
$configPath = Join-Path $installDir "appsettings.json"
Set-Content -Path $configPath -Value $configJson -Encoding UTF8

# Write consent receipt to ProgramData -- uploaded to cloud on first heartbeat
$consentPath = Join-Path $dataDir "consent-receipt.json"
$consentReceipt.pharmacyId = $PharmacyId
$consentReceipt.agentId = $AgentId
$consentJson = $consentReceipt | ConvertTo-Json -Depth 5
Set-Content -Path $consentPath -Value $consentJson -Encoding UTF8
Write-Ok "Consent receipt saved to $consentPath"
Write-Ok "appsettings.json written to $installDir"

# Lock down appsettings (contains SQL credentials)
$acl = Get-Acl $configPath
$acl.SetAccessRuleProtection($true, $false)
$acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "BUILTIN\Administrators", "FullControl", "None", "None", "Allow")))
$acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "NT AUTHORITY\SYSTEM", "FullControl", "None", "None", "Allow")))
$acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "NT AUTHORITY\LOCAL SERVICE", "Modify", "None", "None", "Allow")))
# Defense-in-depth: NetworkService (Broker) doesn't normally load appsettings
# but we grant Read anyway so a future Broker config binding doesn't silently
# break. Broker's Host.CreateEmptyApplicationBuilder intentionally bypasses
# appsettings auto-load; this grant is belt-and-suspenders.
$acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "NT AUTHORITY\NETWORK SERVICE", "Read", "None", "None", "Allow")))
Set-Acl $configPath $acl
Write-Ok "Credentials locked down (Admin + SYSTEM + LocalService M + NetworkService R)"

# ============================================
# PHASE 5: Install Windows services
# ============================================
Write-Step "Phase 5: Installing Windows services"

# Stop + remove existing (watchdog first so it doesn't restart us mid-teardown)
foreach ($svc in @("SuavoAgent.Watchdog", "SuavoAgent.Broker", "SuavoAgent.Core")) {
    $s = Get-Service -Name $svc -ErrorAction SilentlyContinue
    if ($s) {
        if ($s.Status -eq "Running") { Stop-Service $svc -Force; Start-Sleep 2 }
        sc.exe delete $svc 2>$null | Out-Null
        Start-Sleep 1
    }
}

# Install Core (runs as LocalService -- least privilege)
$corePath = Join-Path $installDir "SuavoAgent.Core.exe"
sc.exe create SuavoAgent.Core binPath= "`"$corePath`"" start= delayed-auto obj= "NT AUTHORITY\LocalService" | Out-Null
sc.exe description SuavoAgent.Core "Suavo pharmacy agent - SQL polling, cloud sync" | Out-Null
sc.exe failure SuavoAgent.Core reset= 3600 actions= restart/5000/restart/30000/restart/60000 | Out-Null
sc.exe failureflag SuavoAgent.Core 1 | Out-Null
Write-Ok "SuavoAgent.Core service registered"

# Install Broker (runs as LocalSystem -- per ADR three-process-architecture, only
# SYSTEM has SeAssignPrimaryTokenPrivilege required for CreateProcessAsUser to spawn
# Helper into the user's interactive session. NetworkService configuration silently
# fell through to Process.Start, leaving Helper in Session 0 and SendInput invisible
# to the user's desktop. Field-confirmed 2026-05-05 RunID=97c53a68.)
$brokerPath = Join-Path $installDir "SuavoAgent.Broker.exe"
sc.exe create SuavoAgent.Broker binPath= "`"$brokerPath`"" start= delayed-auto obj= "LocalSystem" | Out-Null
sc.exe description SuavoAgent.Broker "Suavo pharmacy agent - session broker (LocalSystem for CreateProcessAsUser)" | Out-Null
sc.exe failure SuavoAgent.Broker reset= 3600 actions= restart/5000/restart/30000/restart/60000 | Out-Null
sc.exe failureflag SuavoAgent.Broker 1 | Out-Null
sc.exe config SuavoAgent.Broker depend= SuavoAgent.Core | Out-Null
Write-Ok "SuavoAgent.Broker service registered"

# Install Watchdog (runs as LocalSystem -- SCM sc.exe start/query requires it).
# No service dependency -- Watchdog must be able to restart Core/Broker even if
# one of them is broken, so making it depend on either would defeat its purpose.
$watchdogPath = Join-Path $installDir "SuavoAgent.Watchdog.exe"
sc.exe create SuavoAgent.Watchdog binPath= "`"$watchdogPath`"" start= delayed-auto obj= "LocalSystem" | Out-Null
sc.exe description SuavoAgent.Watchdog "Suavo pharmacy agent - process watchdog (auto-restarts Core/Broker, escalates to bootstrap --repair)" | Out-Null
sc.exe failure SuavoAgent.Watchdog reset= 3600 actions= restart/10000/restart/60000/restart/300000 | Out-Null
sc.exe failureflag SuavoAgent.Watchdog 1 | Out-Null
Write-Ok "SuavoAgent.Watchdog service registered"

# Lock down install directory. NetworkService needs ReadAndExecute to load
# and launch SuavoAgent.Broker.exe -- omitting it causes SCM error 7000
# ("system cannot find the file specified") when Broker tries to start.
#
# Phase 5.6: Users:RX added because Helper now spawns into the user's
# interactive session via CreateProcessAsUser. The .NET single-file apphost
# calls realpath() / GetFinalPathNameByHandleW on SuavoAgent.Helper.exe at
# startup, which opens the EXE as the running user; without Users:RX the
# open fails with ACCESS_DENIED and Helper crashes immediately with
# .NET Event 1023 "Failed to resolve full path of the current executable".
# Field-confirmed Queen 2026-05-05 (helper PIDs 11588...1840 all died
# within milliseconds before this rule was added).
$dirAcl = Get-Acl $installDir
$dirAcl.SetAccessRuleProtection($true, $false)
$dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "BUILTIN\Administrators", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")))
$dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "NT AUTHORITY\SYSTEM", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")))
$dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "NT AUTHORITY\LOCAL SERVICE", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow")))
$dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "NT AUTHORITY\NETWORK SERVICE", "ReadAndExecute", "ContainerInherit,ObjectInherit", "None", "Allow")))
$dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "BUILTIN\Users", "ReadAndExecute", "ContainerInherit,ObjectInherit", "None", "Allow")))
Set-Acl $installDir $dirAcl

# Start services. Start-Service's 30s default wait is tight for cold starts
# on .NET 8 single-file self-extracting exes, so we poll manually up to 90s
# and -- if the service still isn't Running -- capture a full post-mortem to
# the operator's Desktop. That way we don't have to ping-pong PowerShell
# diagnostic commands through the operator when something breaks.
function Wait-ServiceRunning {
    param([string]$Name, [int]$TimeoutSec = 90)
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        $svc = Get-Service -Name $Name -ErrorAction SilentlyContinue
        if ($svc -and $svc.Status -eq 'Running') { return $true }
        Start-Sleep -Seconds 2
    }
    return $false
}

function Unprotect-AgentSecret {
    param([AllowNull()][string]$Value)
    if ([string]::IsNullOrWhiteSpace($Value)) { return $Value }
    if (-not $Value.StartsWith("DPAPI:", [System.StringComparison]::Ordinal)) { return $Value }

    Add-Type -AssemblyName System.Security
    $bytes = [Convert]::FromBase64String($Value.Substring(6))
    $plain = [System.Security.Cryptography.ProtectedData]::Unprotect(
        $bytes,
        $null,
        [System.Security.Cryptography.DataProtectionScope]::LocalMachine)
    return [System.Text.Encoding]::UTF8.GetString($plain)
}

function Get-AgentHmacSignature {
    param(
        [string]$ApiKey,
        [string]$Timestamp,
        [string]$Body
    )

    $hmac = New-Object System.Security.Cryptography.HMACSHA256
    $hmac.Key = [System.Text.Encoding]::UTF8.GetBytes($ApiKey)
    $signed = $Timestamp + ":" + $Body
    $bytes = $hmac.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($signed))
    return ([System.BitConverter]::ToString($bytes) -replace "-", "").ToLowerInvariant()
}

function Get-CloudAuthFailureDetail {
    param([object]$ErrorRecord)

    $status = $null
    $reason = $null

    if ($ErrorRecord.Exception.Response) {
        try { $status = [int]$ErrorRecord.Exception.Response.StatusCode } catch { }
        try {
            $stream = $ErrorRecord.Exception.Response.GetResponseStream()
            if ($stream) {
                $reader = New-Object System.IO.StreamReader($stream)
                $body = $reader.ReadToEnd()
                if (-not [string]::IsNullOrWhiteSpace($body)) {
                    $parsed = $body | ConvertFrom-Json
                    if ($parsed.error) {
                        $reason = ([string]$parsed.error) -replace '[^A-Za-z0-9_.-]', '_'
                        if ($reason.Length -gt 80) { $reason = $reason.Substring(0, 80) }
                    }
                }
            }
        } catch {
            $reason = $null
        }
    }

    if ($status -and $reason) { return "http_$status`_$reason" }
    if ($status) { return "http_$status" }
    return "request_failed"
}

function Test-AgentCloudAuth {
    param([string]$ConfigPath)

    if (-not (Test-Path -LiteralPath $ConfigPath -PathType Leaf)) {
        Write-Warn "Cloud auth check skipped -- appsettings.json missing"
        return $false
    }

    try {
        $cfg = Get-Content -LiteralPath $ConfigPath -Raw | ConvertFrom-Json
        $agent = $cfg.Agent
        $cloudBase = ([string]$agent.CloudUrl).TrimEnd([char[]]"/")
        $apiKey = Unprotect-AgentSecret -Value ([string]$agent.ApiKey)

        if ([string]::IsNullOrWhiteSpace($cloudBase) -or [string]::IsNullOrWhiteSpace($apiKey)) {
            Write-Warn "Cloud auth check failed -- missing CloudUrl or ApiKey"
            return $false
        }
        if (-not $cloudBase.StartsWith("https://", [System.StringComparison]::OrdinalIgnoreCase)) {
            Write-Warn "Cloud auth check failed -- CloudUrl must use HTTPS"
            return $false
        }

        $timestamp = [DateTimeOffset]::UtcNow.ToString("o")
        $headers = @{
            "x-agent-api-key" = $apiKey
            "x-agent-timestamp" = $timestamp
            "x-agent-signature" = Get-AgentHmacSignature -ApiKey $apiKey -Timestamp $timestamp -Body ""
        }
        $resp = Invoke-RestMethod -Method GET -Uri "$cloudBase/api/agent/config" -Headers $headers -TimeoutSec 15
        if ($resp -and [bool]$resp.success) {
            Write-Ok "Cloud HMAC auth accepted"
            return $true
        }

        Write-Warn "Cloud auth check failed -- unexpected_response"
        return $false
    } catch {
        $detail = Get-CloudAuthFailureDetail -ErrorRecord $_
        Write-Warn "Cloud auth check failed -- $detail"
        return $false
    } finally {
        $apiKey = $null
    }
}

function Save-StartupPostmortem {
    param([string]$ServiceName, [string]$DumpPath)

    function Redact-PostmortemText {
        param([AllowNull()][string]$Text)
        if ($null -eq $Text) { return "" }

        $redacted = [string]$Text
        $redacted = $redacted -replace '([\\/])Users([\\/])[^\\/\r\n]+', '$1Users$2[REDACTED_USER]'
        $redacted = $redacted -replace '([\\/])home([\\/])[^\\/\r\n]+', '$1home$2[REDACTED_USER]'
        $redacted = $redacted -replace '\b\d{3}-\d{2}-\d{4}\b', '[REDACTED_SSN]'
        $redacted = $redacted -replace '\bRx#?\s*\d{7,12}\b', '[REDACTED_RX]'
        $redacted = $redacted -replace '\b\d{3}[-.\s]\d{3}[-.\s]\d{4}\b', '[REDACTED_PHONE]'
        $redacted = $redacted -replace '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', '[REDACTED_EMAIL]'
        $redacted = $redacted -replace '\bMRN[:\s#]?\s*\d+\b', '[REDACTED_MRN]'
        $redacted = $redacted -replace '\b(0?[1-9]|1[0-2])/(0?[1-9]|[12]\d|3[01])/(19|20)\d{2}\b', '[REDACTED_DATE]'
        $redacted = $redacted -replace '"[^"]{65,}"', '"[REDACTED_LONG_STRING]"'
        return $redacted
    }

    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("SuavoAgent service start post-mortem")
    $lines.Add("Service: $ServiceName")
    $lines.Add("Timestamp: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')")
    $lines.Add("Machine: $env:COMPUTERNAME")
    $lines.Add("Release: $ReleaseTag")
    $lines.Add("")
    $lines.Add("=== Get-Service ===")
    try {
        $svc = Get-Service -Name $ServiceName -ErrorAction Stop
        $lines.Add(($svc | Format-List Name,Status,StartType,DisplayName | Out-String).Trim())
    } catch { $lines.Add("Get-Service failed: $($_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== sc.exe qc (config) ===")
    try {
        $qc = sc.exe qc $ServiceName 2>&1 | Out-String
        $lines.Add($qc.Trim())
    } catch { $lines.Add("sc qc failed: $($_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== sc.exe queryex (state + exit code) ===")
    try {
        $qex = sc.exe queryex $ServiceName 2>&1 | Out-String
        $lines.Add($qex.Trim())
    } catch { $lines.Add("sc queryex failed: $($_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== Recent System log (SCM) ===")
    try {
        $sys = Get-WinEvent -FilterHashtable @{
            LogName      = 'System'
            ProviderName = 'Service Control Manager'
            StartTime    = (Get-Date).AddMinutes(-10)
        } -ErrorAction SilentlyContinue |
            Where-Object { $_.Message -match 'Suavo' } |
            Select-Object -First 10
        if ($sys) { $lines.Add((Redact-PostmortemText -Text (($sys | Format-List TimeCreated,LevelDisplayName,Id,Message | Out-String).Trim()))) }
        else { $lines.Add("(no SCM events matching 'Suavo' in the last 10 min)") }
    } catch { $lines.Add("System log query failed: $(Redact-PostmortemText -Text $_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== Recent Application log (.NET Runtime + Application Error) ===")
    try {
        $app = Get-WinEvent -FilterHashtable @{
            LogName   = 'Application'
            StartTime = (Get-Date).AddMinutes(-10)
        } -ErrorAction SilentlyContinue |
            Where-Object { $_.ProviderName -match '\.NET Runtime|Application Error|\.NET Host' -or $_.Message -match 'Suavo' } |
            Select-Object -First 15
        if ($app) { $lines.Add((Redact-PostmortemText -Text (($app | Format-List TimeCreated,LevelDisplayName,ProviderName,Id,Message | Out-String).Trim()))) }
        else { $lines.Add("(no matching Application events in the last 10 min)") }
    } catch { $lines.Add("Application log query failed: $(Redact-PostmortemText -Text $_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== Agent install dir listing ===")
    try {
        $ls = Get-ChildItem $installDir -Force | Select-Object Name, Length, LastWriteTime | Format-Table | Out-String
        $lines.Add($ls.Trim())
    } catch { $lines.Add("install dir listing failed: $(Redact-PostmortemText -Text $_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== Core startup-crash.log (written by last-resort crash sink) ===")
    $crashLog = Join-Path $env:ProgramData "SuavoAgent\logs\startup-crash.log"
    if (Test-Path $crashLog) {
        try { $lines.Add((Redact-PostmortemText -Text ((Get-Content $crashLog -Raw).Trim()))) }
        catch { $lines.Add("crash log read failed: $(Redact-PostmortemText -Text $_.Exception.Message)") }
    } else {
        $lines.Add("(startup-crash.log not present -- process died before crash sink ran)")
    }
    $lines.Add("")
    $lines.Add("=== Broker broker-crash.log (written by last-resort crash sink) ===")
    $brokerCrashLog = Join-Path $env:ProgramData "SuavoAgent\logs\broker-crash.log"
    if (Test-Path $brokerCrashLog) {
        try { $lines.Add((Redact-PostmortemText -Text ((Get-Content $brokerCrashLog -Raw).Trim()))) }
        catch { $lines.Add("broker crash log read failed: $(Redact-PostmortemText -Text $_.Exception.Message)") }
    } else {
        $lines.Add("(broker-crash.log not present)")
    }
    $lines.Add("")
    $lines.Add("=== Broker Serilog broker-*.log (last 80 lines) ===")
    $brokerLogDir = Join-Path $env:ProgramData "SuavoAgent\logs"
    if (Test-Path $brokerLogDir) {
        $brokerLatest = Get-ChildItem $brokerLogDir -Filter 'broker-*.log' -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending | Select-Object -First 1
        if ($brokerLatest) {
            try { $lines.Add((Redact-PostmortemText -Text ((Get-Content $brokerLatest.FullName -Tail 80 | Out-String).Trim()))) }
            catch { $lines.Add("broker log read failed: $(Redact-PostmortemText -Text $_.Exception.Message)") }
        } else {
            $lines.Add("(no broker-*.log found -- Broker never reached Serilog init)")
        }
    }
    $lines.Add("")
    $lines.Add("=== Core Serilog startup-YYYYMMDD.log (last 80 lines) ===")
    $startupLogDir = Join-Path $env:ProgramData "SuavoAgent\logs"
    if (Test-Path $startupLogDir) {
        $latest = Get-ChildItem $startupLogDir -Filter 'startup-*.log' -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending | Select-Object -First 1
        if ($latest) {
            try { $lines.Add((Redact-PostmortemText -Text ((Get-Content $latest.FullName -Tail 80 | Out-String).Trim()))) }
            catch { $lines.Add("startup log read failed: $(Redact-PostmortemText -Text $_.Exception.Message)") }
        } else {
            $lines.Add("(no startup-*.log found)")
        }
    } else {
        $lines.Add("(ProgramData\SuavoAgent\logs not present -- service never reached Serilog init)")
    }

    $text = ($lines -join [Environment]::NewLine)
    [System.IO.File]::WriteAllText($DumpPath, $text)
}

$installFailed = $false

Write-Host "  Starting SuavoAgent.Core (up to 90s)..." -ForegroundColor Gray
try { Start-Service SuavoAgent.Core -ErrorAction Stop } catch {
    # Start-Service can throw even when the service is in StartPending;
    # swallow here and let the poll below be the source of truth.
}
if (Wait-ServiceRunning -Name 'SuavoAgent.Core' -TimeoutSec 90) {
    Write-Ok "SuavoAgent.Core is running"
} else {
    $dumpPath = Join-Path $env:USERPROFILE "Desktop\suavo-service-postmortem-$(Get-Date -Format 'yyyyMMdd-HHmmss').txt"
    Save-StartupPostmortem -ServiceName 'SuavoAgent.Core' -DumpPath $dumpPath
    $dumpTail = if (Test-Path $dumpPath -PathType Leaf) { Get-Content -Path $dumpPath -Raw -ErrorAction SilentlyContinue } else { $null }
    Write-Fail "SuavoAgent.Core did not reach Running within 90s"
    Write-Host "  Post-mortem saved to: $dumpPath" -ForegroundColor Yellow
    Write-Host "  Send that file to whoever is helping and they will have everything needed to diagnose." -ForegroundColor Yellow
    Send-InstallTelemetry -Stage "service_start_core" -Level "fatal" -Message "SuavoAgent.Core did not reach Running within 90s" -ExitCode 1 -StdoutTail $dumpTail
    $installFailed = $true
}

Write-Host "  Starting SuavoAgent.Broker..." -ForegroundColor Gray
try { Start-Service SuavoAgent.Broker -ErrorAction Stop } catch { }
if (-not (Wait-ServiceRunning -Name 'SuavoAgent.Broker' -TimeoutSec 60)) {
    $brokerDump = Join-Path $env:USERPROFILE "Desktop\suavo-broker-postmortem-$(Get-Date -Format 'yyyyMMdd-HHmmss').txt"
    Save-StartupPostmortem -ServiceName 'SuavoAgent.Broker' -DumpPath $brokerDump
    $brokerDumpTail = if (Test-Path $brokerDump -PathType Leaf) { Get-Content -Path $brokerDump -Raw -ErrorAction SilentlyContinue } else { $null }
    Write-Host "  Broker did not start within 60s -- post-mortem at $brokerDump" -ForegroundColor Yellow
    Send-InstallTelemetry -Stage "service_start_broker" -Level "fatal" -Message "SuavoAgent.Broker did not reach Running within 60s" -ExitCode 1 -StdoutTail $brokerDumpTail
    $installFailed = $true
}

# Stash this bootstrap so Watchdog's --repair escalation can invoke it even
# if the operator installed via `irm|iex` (no on-disk script). Download the
# pinned release tag from raw.githubusercontent.com so the persisted copy
# matches the binaries we just installed.
try {
    $bootstrapUrl = "https://raw.githubusercontent.com/$RepoOwner/$RepoName/$ReleaseTag/bootstrap.ps1"
    $bootstrapDst = Join-Path $dataDir "bootstrap.ps1"
    Invoke-WebRequest -Uri $bootstrapUrl -OutFile $bootstrapDst -UseBasicParsing -TimeoutSec 30
    Write-Ok "Bootstrap script persisted to $bootstrapDst for watchdog --repair escalation"
} catch {
    Write-Host "  Bootstrap persistence skipped: $($_.Exception.Message)" -ForegroundColor DarkGray
}

Write-Host "  Starting SuavoAgent.Watchdog..." -ForegroundColor Gray
try { Start-Service SuavoAgent.Watchdog -ErrorAction Stop } catch { }
if (-not (Wait-ServiceRunning -Name 'SuavoAgent.Watchdog' -TimeoutSec 60)) {
    $wdDump = Join-Path $env:USERPROFILE "Desktop\suavo-watchdog-postmortem-$(Get-Date -Format 'yyyyMMdd-HHmmss').txt"
    Save-StartupPostmortem -ServiceName 'SuavoAgent.Watchdog' -DumpPath $wdDump
    $wdDumpTail = if (Test-Path $wdDump -PathType Leaf) { Get-Content -Path $wdDump -Raw -ErrorAction SilentlyContinue } else { $null }
    Write-Host "  Watchdog did not start within 60s -- post-mortem at $wdDump" -ForegroundColor Yellow
    Send-InstallTelemetry -Stage "service_start_watchdog" -Level "fatal" -Message "SuavoAgent.Watchdog did not reach Running within 60s" -ExitCode 1 -StdoutTail $wdDumpTail
    $installFailed = $true
}

# ============================================
# PHASE 6: Verify
# ============================================
Write-Step "Phase 6: Verification"

foreach ($svc in @("SuavoAgent.Core", "SuavoAgent.Broker", "SuavoAgent.Watchdog")) {
    $s = Get-Service -Name $svc -ErrorAction SilentlyContinue
    if ($s -and $s.Status -eq "Running") {
        Write-Ok "$svc is running"
    } else {
        Write-Warn "$svc status: $($s.Status)"
        $installFailed = $true
    }
}

# Verify cloud authentication before declaring install complete. This catches
# the dangerous false-green state where Windows services are alive but the
# cloud rejects every heartbeat/config poll with 401 Agent not found.
if (-not (Test-AgentCloudAuth -ConfigPath $configPath)) {
    $installFailed = $true
    Send-InstallTelemetry -Stage "cloud_auth_verify" -Level "fatal" -Message "Cloud HMAC auth failed during final install verification" -ExitCode 1
}

if ($installFailed) {
    Write-Fail "SuavoAgent install did not pass startup verification"
    Write-Host "  At least one required service or cloud-auth check failed." -ForegroundColor Yellow
    Write-Host "  Use the cloud-auth line above, any post-mortem file(s) on the Desktop, and $dataDir\logs\ for debugging." -ForegroundColor Yellow
    Send-InstallTelemetry -Stage "service_verify" -Level "fatal" -Message "SuavoAgent install did not pass startup verification" -ExitCode 1
    try { Stop-Transcript -ErrorAction SilentlyContinue | Out-Null } catch { }
    exit 1
}

Write-Host ""
Write-Host "  +===========================================+" -ForegroundColor Green
Write-Host "  |   SuavoAgent v3 -- Installation Complete   |" -ForegroundColor Green
Write-Host "  +===========================================+" -ForegroundColor Green
Write-Host ""
Write-Host "  Install:  $installDir" -ForegroundColor White
Write-Host "  Data:     $dataDir" -ForegroundColor White
Write-Host "  Logs:     $dataDir\logs\" -ForegroundColor White
Write-Host "  Config:   $configPath" -ForegroundColor White
Write-Host "  Agent ID: $AgentId" -ForegroundColor White
Write-Host ""
if ($sqlServer) {
    Write-Host "  SQL:      $sqlServer / $sqlDatabase" -ForegroundColor White
    Write-Host "  Auth:     $(if ($sqlUser) { "SQL ($sqlUser)" } else { 'Windows' })" -ForegroundColor White
} else {
    Write-Host "  SQL:      (deferred -- agent will auto-discover during learning phase)" -ForegroundColor Gray
}
Write-Host ""

Get-ChildItem "$installDir\*.exe" | ForEach-Object {
    $sizeMb = [math]::Round($_.Length / 1MB, 1)
    Write-Host "  $($_.Name) -- $sizeMb MB" -ForegroundColor Gray
}

Write-Host ""
Write-Host "  Agent will query for delivery-ready Rxs every 5 minutes." -ForegroundColor Cyan
Write-Host "  Check logs: Get-Content $dataDir\logs\core-*.log -Tail 50" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Install log: $transcriptPath" -ForegroundColor Gray

# Clean up install transcript on success
try {
    $script:InstallTelemetryToken = $null
    Stop-Transcript -ErrorAction SilentlyContinue | Out-Null
    if ($transcriptPath -and (Test-Path $transcriptPath)) {
        Remove-Item $transcriptPath -Force -ErrorAction SilentlyContinue
        Write-Ok "Install transcript cleaned up"
    }
} catch { }
