# SuavoAgent -- Zero-Config One-Paste Installer
#
# INSTALL (paste into Admin PowerShell):
#   Set-ExecutionPolicy Bypass -Scope Process -Force; irm https://raw.githubusercontent.com/MinaH153/SuavoAgent/main/bootstrap.ps1 -OutFile $env:TEMP\bs.ps1; & $env:TEMP\bs.ps1
#
# By default resolves the latest published release from GitHub. To pin a
# specific version (e.g. for rollback testing), pass -ReleaseTag v3.10.5.
#
# What it does:
# 1. Detects pharmacy management system (PioneerRx, or none)
# 2. Discovers SQL credentials if PMS found
# 3. Downloads signed agent binaries from GitHub
# 4. Writes appsettings.json with discovered credentials
# 5. Installs + starts Windows services
# 6. Agent auto-discovers PMS during learning phase if not detected at install
#
# SAFETY: ConnectionStringServer is called ONCE. Agent uses MaxPoolSize=1.
# Never disrupts pharmacy operations.

param(
    [string]$PharmacyId,
    [string]$ApiKey,
    # Single-use install token generated by the dashboard. When provided, the
    # bootstrap calls /api/agent/register to exchange it for a pharmacy-scoped
    # API key + pharmacy id instead of requiring them up-front. This is the
    # path used by the dashboard onboarding flow.
    [string]$InstallToken,
    [string]$CloudUrl = "https://suavollc.com",
    [switch]$LearningMode,
    # Empty = auto-resolve the latest published release via the GitHub API.
    # Pass an explicit v-tag (e.g. -ReleaseTag v3.10.5) to pin a version.
    [string]$ReleaseTag = "",
    [string]$RepoOwner = "MinaH153",
    [string]$RepoName = "SuavoAgent",
    [switch]$SkipConsent
)

# Auto-log everything -- transcript saved to desktop for debugging
$transcriptPath = "$env:USERPROFILE\Desktop\suavo-install-$(Get-Date -Format 'yyyyMMdd-HHmmss').log"
Start-Transcript -Path $transcriptPath -Force | Out-Null

$ErrorActionPreference = "Stop"
$installDir = "C:\Program Files\Suavo\Agent"
$dataDir = "$env:ProgramData\SuavoAgent"

function Resolve-ReleaseTag {
    param(
        [string]$TagOrEmpty,
        [string]$Owner,
        [string]$Repo
    )
    if (-not [string]::IsNullOrWhiteSpace($TagOrEmpty)) {
        if ($TagOrEmpty -notmatch '^v\d+\.\d+\.\d+') {
            throw "Invalid release tag format: $TagOrEmpty"
        }
        Write-Host "  Pinned release: $TagOrEmpty" -ForegroundColor DarkGray
        return $TagOrEmpty
    }

    # Fetch latest release metadata. API returns { tag_name: "v3.10.5", ... }.
    $apiUrl = "https://api.github.com/repos/$Owner/$Repo/releases/latest"
    Write-Host "  Resolving latest release from $apiUrl" -ForegroundColor DarkGray
    try {
        $meta = Invoke-RestMethod -Uri $apiUrl -UserAgent "SuavoAgent-Bootstrap" -TimeoutSec 30
    } catch {
        throw "Failed to fetch latest release metadata: $($_.Exception.Message)"
    }

    $tag = $meta.tag_name
    if (-not $tag -or $tag -notmatch '^v\d+\.\d+\.\d+') {
        throw "GitHub returned unexpected tag: '$tag'"
    }
    Write-Host "  Auto-resolved latest release: $tag" -ForegroundColor Green
    return $tag
}

$ReleaseTag = Resolve-ReleaseTag -TagOrEmpty $ReleaseTag -Owner $RepoOwner -Repo $RepoName
$base = "https://github.com/$RepoOwner/$RepoName/releases/download/$ReleaseTag"

function Write-Step($msg) { Write-Host "`n[$((Get-Date).ToString('HH:mm:ss'))] $msg" -ForegroundColor Cyan }
function Write-Ok($msg) { Write-Host "  [OK] $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "  [WARN] $msg" -ForegroundColor Yellow }
function Write-Fail($msg) { Write-Host "  [FAIL] $msg" -ForegroundColor Red }

# -- Require Admin --
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
    [Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Fail "Run as Administrator"
    exit 1
}

# -- Learning mode prompt (if not explicitly set via flag) --
if (-not $PSBoundParameters.ContainsKey('LearningMode')) {
    $lmResponse = Read-Host "Enable learning mode? (30-day observation before automation) [y/N]"
    if ($lmResponse -eq 'y' -or $lmResponse -eq 'Y') {
        $LearningMode = [switch]::new($true)
    }
}

Write-Host ""
Write-Host "  +=======================================+" -ForegroundColor Cyan
Write-Host "  |   SuavoAgent v3 -- Zero-Config Setup   |" -ForegroundColor Cyan
Write-Host "  +=======================================+" -ForegroundColor Cyan
Write-Host ""

# ============================================
# TERMS OF SERVICE + EMPLOYEE MONITORING CONSENT
# ============================================
# This consent is recorded digitally and uploaded to the Suavo cloud
# on first heartbeat. No separate paperwork needed.
if (-not $SkipConsent) {
Write-Host ""
Write-Host "  ╔══════════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║         SUAVOAGENT TERMS & CONSENT                  ║" -ForegroundColor Cyan
Write-Host "  ╚══════════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""
Write-Host "  SuavoAgent is workplace monitoring software that observes" -ForegroundColor White
Write-Host "  business workstation activity to optimize delivery operations." -ForegroundColor White
Write-Host ""
Write-Host "  WHAT IT COLLECTS:" -ForegroundColor Yellow
Write-Host "    - Application usage patterns and durations" -ForegroundColor Gray
Write-Host "    - Workstation hardware profile" -ForegroundColor Gray
Write-Host "    - Login/logout timing (shift patterns)" -ForegroundColor Gray
Write-Host "    - Website domain categories (NOT specific URLs)" -ForegroundColor Gray
Write-Host "    - Print event counts (NOT document content)" -ForegroundColor Gray
Write-Host ""
Write-Host "  WHAT IT NEVER COLLECTS:" -ForegroundColor Green
Write-Host "    - Keystrokes, passwords, or typed text" -ForegroundColor Gray
Write-Host "    - Screen captures or screenshots" -ForegroundColor Gray
Write-Host "    - Email, message, or chat content" -ForegroundColor Gray
Write-Host "    - Personal browsing history or specific URLs" -ForegroundColor Gray
Write-Host "    - File contents or document data" -ForegroundColor Gray
Write-Host ""
Write-Host "  LEGAL REQUIREMENTS:" -ForegroundColor Red
Write-Host "    CT, DE, NY: Written notice to each employee REQUIRED by law" -ForegroundColor Red
Write-Host "    CA: CCPA notice at collection required" -ForegroundColor Red
Write-Host "    All states: Employee notification is recommended best practice" -ForegroundColor Yellow
Write-Host ""
Write-Host "  BY PROCEEDING, THE AUTHORIZING PARTY CONFIRMS:" -ForegroundColor Yellow
Write-Host "    1. Authorization to install monitoring software on this machine" -ForegroundColor White
Write-Host "    2. Responsibility to notify all employees per applicable state laws" -ForegroundColor White
Write-Host "    3. Agreement to Suavo's Terms of Service and Privacy Policy" -ForegroundColor White
Write-Host "    4. Execution of Business Associate Agreement (if healthcare)" -ForegroundColor White
Write-Host ""

# Collect authorizing party info — this gets recorded in the consent receipt
$authName = Read-Host "  Authorizing party full name"
if ([string]::IsNullOrWhiteSpace($authName)) {
    Write-Host "  Installation cancelled — authorizing party name required." -ForegroundColor Red
    exit 0
}
$authTitle = Read-Host "  Title (e.g., Owner, Pharmacy Manager)"
if ([string]::IsNullOrWhiteSpace($authTitle)) { $authTitle = "Authorized Representative" }

$confirmState = Read-Host "  State where this business operates (e.g., CA, NY, TX)"
if ([string]::IsNullOrWhiteSpace($confirmState)) { $confirmState = "Unknown" }

# Check if mandatory notice state
$mandatoryNoticeStates = @("CT","DE","NY")
$highRiskStates = @("CA","IL","MA","MD","CO","MT")
$stateUpper = $confirmState.ToUpper().Trim()
if ($mandatoryNoticeStates -contains $stateUpper) {
    Write-Host ""
    Write-Host "  *** $stateUpper REQUIRES written employee notice before monitoring ***" -ForegroundColor Red
    Write-Host "  You MUST distribute the employee notice template to all staff" -ForegroundColor Red
    Write-Host "  at this workstation BEFORE SuavoAgent begins collecting data." -ForegroundColor Red
    Write-Host ""
    $noticeConfirm = Read-Host "  Type CONFIRMED to acknowledge this legal requirement"
    if ($noticeConfirm -ne "CONFIRMED") {
        Write-Host "  Installation cancelled — employee notice acknowledgment required in $stateUpper." -ForegroundColor Red
        exit 0
    }
} elseif ($highRiskStates -contains $stateUpper) {
    Write-Host ""
    Write-Host "  NOTE: $stateUpper has strong privacy protections. Employee notice is" -ForegroundColor Yellow
    Write-Host "  strongly recommended even if not strictly required by statute." -ForegroundColor Yellow
    Write-Host ""
}

Write-Host ""
$finalConfirm = Read-Host "  Type AGREE to accept terms and proceed with installation"
if ($finalConfirm -ne "AGREE") {
    Write-Host "  Installation cancelled." -ForegroundColor Red
    exit 0
}

# Build consent receipt — saved locally and uploaded on first heartbeat
$consentTimestamp = (Get-Date).ToString("o")
$consentReceipt = @{
    consentVersion = "1.0"
    authorizingParty = @{
        name = $authName
        title = $authTitle
    }
    businessState = $stateUpper
    mandatoryNoticeState = ($mandatoryNoticeStates -contains $stateUpper)
    consentTimestamp = $consentTimestamp
    termsAccepted = $true
    employeeNoticeAcknowledged = ($mandatoryNoticeStates -contains $stateUpper)
    installerVersion = "3.8.0"
    machineFingerprint = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Cryptography').MachineGuid
}
Write-Ok "Consent recorded: $authName ($authTitle) at $consentTimestamp"
Write-Host ""
} else {
    Write-Ok "Consent recorded via web dashboard — skipping terminal prompts"
    # Set defaults for the consent receipt (already recorded in cloud)
    $authName = "Web Dashboard"
    $authTitle = "Pre-authorized"
    $confirmState = "WEB"
    $consentTimestamp = (Get-Date).ToString("o")
    $consentReceipt = @{
        consentVersion = "1.0"
        authorizingParty = @{ name = $authName; title = $authTitle }
        businessState = $confirmState
        mandatoryNoticeState = $false
        consentTimestamp = $consentTimestamp
        termsAccepted = $true
        employeeNoticeAcknowledged = $true
        installerVersion = "3.9.1"
        machineFingerprint = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Cryptography').MachineGuid
        source = "web_dashboard"
    }
}

# ============================================
# PHASE 1: Detect Pharmacy Management System
# ============================================
Write-Step "Phase 1: Detecting pharmacy management system"

$pmsType = $null
$pioneerDir = $null
$pioneerExe = $null
$pioneerConfig = $null

# --- PioneerRx detection ---
$pioneerPaths = @(
    "C:\Program Files (x86)\New Tech Computer Systems\PioneerRx",
    "C:\Program Files\New Tech Computer Systems\PioneerRx",
    "D:\Program Files (x86)\New Tech Computer Systems\PioneerRx",
    "D:\Program Files\New Tech Computer Systems\PioneerRx"
)
try {
    $regPaths = @(
        "HKLM:\SOFTWARE\WOW6432Node\New Tech Computer Systems",
        "HKLM:\SOFTWARE\New Tech Computer Systems"
    )
    foreach ($rp in $regPaths) {
        if (Test-Path $rp) {
            $regInstall = (Get-ItemProperty $rp -ErrorAction SilentlyContinue).InstallPath
            if ($regInstall) { $pioneerPaths = @($regInstall) + $pioneerPaths }
        }
    }
} catch {}
foreach ($p in $pioneerPaths) {
    # [hotfix] Use IO.Path.Combine (string concat only) instead of Join-Path
    # which validates the drive exists and throws on e.g. "D:\..." when D:
    # isn't mounted. Test-Path handles non-existent drives cleanly (returns
    # $false) so the loop skips missing candidates without dying.
    $exe = [System.IO.Path]::Combine($p, "PioneerPharmacy.exe")
    $cfg = [System.IO.Path]::Combine($p, "PioneerPharmacy.exe.config")
    if ((Test-Path $exe) -and (Test-Path $cfg)) {
        $pioneerDir = $p; $pioneerExe = $exe; $pioneerConfig = $cfg; $pmsType = "PioneerRx"
        break
    }
}
if (-not $pmsType) {
    $proc = Get-Process -Name "PioneerPharmacy" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($proc) {
        $pioneerExe = $proc.Path; $pioneerDir = Split-Path $pioneerExe -Parent
        $pioneerConfig = "$pioneerExe.config"; $pmsType = "PioneerRx"
    }
}

# --- Future PMS detections go here ---
# QS/1: Check for "QS1.exe" or registry
# Liberty: Check for "Liberty.exe" or known paths
# McKesson: Check for "EnterpriseRx" paths
# Each sets $pmsType and relevant config vars

# --- Result ---
if ($pmsType) {
    Write-Ok "Detected: $pmsType at $pioneerDir"
} else {
    Write-Warn "No pharmacy management system detected on this machine"
    Write-Host "  The agent will install and auto-discover the PMS during its learning phase." -ForegroundColor Gray
    Write-Host "  Supported: PioneerRx (more adapters coming)" -ForegroundColor Gray
    Write-Host ""
}

# ============================================
# PHASE 2: Extract SQL credentials
# ============================================
# Pause transcript during credential discovery — SQL passwords must not be logged
try { Stop-Transcript -ErrorAction SilentlyContinue | Out-Null } catch { }

if (-not $pmsType) {
    Write-Step "Phase 2: Skipping SQL discovery (no PMS detected)"
    $sqlServer = ""
    $sqlDatabase = ""
    $sqlUser = $null
    $sqlPassword = $null
    Write-Host "  Agent will discover SQL during learning phase" -ForegroundColor Gray
} else {
    Write-Step "Phase 2: Discovering SQL Server credentials"
}

if ($pmsType) {
$sqlServer = $null
$sqlDatabase = "PioneerPharmacySystem"
$sqlUser = $null
$sqlPassword = $null

# Step 2a: Read config for host
$configXml = [xml](Get-Content $pioneerConfig)
$pioneerHost = $null

# Try newTechDataConfiguration element
$ntdc = $configXml.configuration.newTechDataConfiguration
if ($ntdc) {
    $pioneerHost = $ntdc.host
    if (-not $pioneerHost) { $pioneerHost = $ntdc.server }
    if (-not $pioneerHost) { $pioneerHost = $ntdc.GetAttribute("host") }
}

# Fallback: search all attributes for host-like values
if (-not $pioneerHost) {
    $configText = Get-Content $pioneerConfig -Raw
    if ($configText -match 'host\s*=\s*"([^"]+)"') {
        $pioneerHost = $Matches[1]
    } elseif ($configText -match 'server\s*=\s*"([^"]+)"') {
        $pioneerHost = $Matches[1]
    }
}

if ($pioneerHost) {
    Write-Ok "PioneerRx host: $pioneerHost"
} else {
    Write-Warn "Could not extract host from config -- will try localhost"
    $pioneerHost = "localhost"
}

# Step 2b: Load Enterprise Library DLL and call ConnectionStringServer
$entLibDll = Join-Path $pioneerDir "Microsoft.Practices.EnterpriseLibrary.Data.dll"
$discoveredConnStr = $null

if (Test-Path $entLibDll) {
    Write-Host "  Loading Enterprise Library DLL..." -ForegroundColor Gray
    try {
        [System.Reflection.Assembly]::LoadFrom($entLibDll) | Out-Null

        # Find the method -- it may be in different classes depending on version
        $dataTypes = [AppDomain]::CurrentDomain.GetAssemblies() |
            Where-Object { $_.GetName().Name -eq "Microsoft.Practices.EnterpriseLibrary.Data" } |
            ForEach-Object { $_.GetTypes() } |
            Where-Object { $_.GetMethods([System.Reflection.BindingFlags]::Static -bor [System.Reflection.BindingFlags]::Public -bor [System.Reflection.BindingFlags]::NonPublic) |
                Where-Object { $_.Name -like "*ConnectionString*Network*" -or $_.Name -like "*Retrieve*Connection*" } }

        foreach ($type in $dataTypes) {
            $methods = $type.GetMethods([System.Reflection.BindingFlags]::Static -bor [System.Reflection.BindingFlags]::Public -bor [System.Reflection.BindingFlags]::NonPublic) |
                Where-Object { $_.Name -like "*ConnectionString*" -or $_.Name -like "*Retrieve*" }
            foreach ($method in $methods) {
                $params = $method.GetParameters()
                if ($params.Count -ge 2) {
                    Write-Host "  Found method: $($type.FullName).$($method.Name)($($params | ForEach-Object { $_.ParameterType.Name } | Join-String ', '))" -ForegroundColor Gray
                    try {
                        if ($params.Count -eq 3) {
                            $discoveredConnStr = $method.Invoke($null, @($sqlDatabase, $pioneerHost, 12345))
                        } elseif ($params.Count -eq 2) {
                            $discoveredConnStr = $method.Invoke($null, @($sqlDatabase, $pioneerHost))
                        }
                        if ($discoveredConnStr) {
                            Write-Ok "ConnectionStringServer returned credentials"
                            break
                        }
                    } catch {
                        Write-Host "    Method call failed: $($_.Exception.InnerException.Message)" -ForegroundColor Gray
                    }
                }
            }
            if ($discoveredConnStr) { break }
        }
    } catch {
        Write-Warn "Enterprise Library DLL load failed: $($_.Exception.Message)"
    }
}

# Step 2c: Try direct TCP to ConnectionStringServer port 12345
if (-not $discoveredConnStr) {
    Write-Host "  Trying direct TCP to ${pioneerHost}:12345..." -ForegroundColor Gray
    try {
        $tcp = New-Object System.Net.Sockets.TcpClient
        $tcp.Connect($pioneerHost, 12345)
        $stream = $tcp.GetStream()
        $stream.ReadTimeout = 5000
        $stream.WriteTimeout = 5000

        # Send database name request (common protocol: length-prefixed UTF-8 string)
        $reqBytes = [System.Text.Encoding]::UTF8.GetBytes($sqlDatabase)
        $lenBytes = [BitConverter]::GetBytes([int32]$reqBytes.Length)
        $stream.Write($lenBytes, 0, 4)
        $stream.Write($reqBytes, 0, $reqBytes.Length)
        $stream.Flush()

        # Read response
        $buf = New-Object byte[] 4096
        $read = $stream.Read($buf, 0, $buf.Length)
        if ($read -gt 0) {
            # Try reading as length-prefixed
            $respStr = [System.Text.Encoding]::UTF8.GetString($buf, 0, $read)
            # Skip length prefix bytes if present
            if ($respStr.Length -gt 4 -and $respStr.Substring(4) -match "Data Source|Server") {
                $discoveredConnStr = $respStr.Substring(4)
            } elseif ($respStr -match "Data Source|Server") {
                $discoveredConnStr = $respStr.TrimStart([char]0, [char]1, [char]2, [char]3, [char]4, [char]5)
            }
            if ($discoveredConnStr) {
                Write-Ok "Got connection string from TCP port 12345"
            }
        }
        $tcp.Close()
    } catch {
        Write-Host "    TCP probe failed: $($_.Exception.Message)" -ForegroundColor Gray
    }
}

# Step 2d: Parse connection string if discovered
if ($discoveredConnStr) {
    Write-Host "  Parsing connection string..." -ForegroundColor Gray
    try {
        $csb = New-Object System.Data.SqlClient.SqlConnectionStringBuilder($discoveredConnStr)
        $sqlServer = $csb.DataSource
        $sqlDatabase = if ($csb.InitialCatalog) { $csb.InitialCatalog } else { $sqlDatabase }
        if (-not $csb.IntegratedSecurity) {
            $sqlUser = $csb.UserID
            $sqlPassword = $csb.Password
        }
        Write-Ok "SQL Server: $sqlServer"
        Write-Ok "Database: $sqlDatabase"
        Write-Ok "Auth: $(if ($sqlUser) { 'SQL Auth as ' + $sqlUser } else { 'Windows Auth' })"
    } catch {
        Write-Warn "Connection string parse failed: $($_.Exception.Message)"
    }
}

# Step 2e: Fallback -- SQL Browser discovery
if (-not $sqlServer) {
    Write-Host "  Trying SQL Browser on $pioneerHost..." -ForegroundColor Gray
    try {
        $udp = New-Object System.Net.Sockets.UdpClient
        $udp.Client.ReceiveTimeout = 3000
        $ep = New-Object System.Net.IPEndPoint([System.Net.IPAddress]::Parse(
            ([System.Net.Dns]::GetHostAddresses($pioneerHost) | Where-Object { $_.AddressFamily -eq 'InterNetwork' } | Select-Object -First 1).IPAddressToString
        ), 1434)
        $udp.Send(@(0x02), 1, $ep) | Out-Null
        $recvEp = New-Object System.Net.IPEndPoint([System.Net.IPAddress]::Any, 0)
        $resp = $udp.Receive([ref]$recvEp)
        $respStr = [System.Text.Encoding]::ASCII.GetString($resp, 3, $resp.Length - 3)
        $udp.Close()

        # Parse "InstanceName;NEWTECH;;tcp;49202;..."
        $parts = $respStr.Split(';')
        $instance = $null; $port = $null
        for ($i = 0; $i -lt $parts.Length - 1; $i++) {
            if ($parts[$i] -eq "InstanceName") { $instance = $parts[$i+1] }
            if ($parts[$i] -eq "tcp" -and $parts[$i+1] -match '^\d+$') { $port = $parts[$i+1] }
        }
        if ($port) {
            $resolvedIp = ([System.Net.Dns]::GetHostAddresses($pioneerHost) |
                Where-Object { $_.AddressFamily -eq 'InterNetwork' } |
                Select-Object -First 1).IPAddressToString
            $sqlServer = "${resolvedIp},${port}"
            Write-Ok "SQL Browser found: $sqlServer (instance: $instance)"
        }
    } catch {
        Write-Host "    SQL Browser failed: $($_.Exception.Message)" -ForegroundColor Gray
    }
}

# Step 2f: If we still have no credentials, prompt
if (-not $sqlServer) {
    Write-Warn "Auto-discovery failed. Manual entry required."
    $sqlServer = Read-Host "  SQL Server (e.g. 192.168.1.78,49202)"
}
if (-not $sqlUser -and -not $discoveredConnStr) {
    Write-Warn "No SQL credentials discovered."
    $needAuth = Read-Host "  Use SQL Auth? (y/n)"
    if ($needAuth -eq 'y') {
        $sqlUser = Read-Host "  SQL Username"
        $sqlPassword = Read-Host "  SQL Password"
    }
}
} # end if ($pmsType)

# Resume transcript — credentials are now in variables, not transcript
try { Start-Transcript -Path $transcriptPath -Append -ErrorAction SilentlyContinue | Out-Null } catch { }

Write-Host ""
if ($pmsType) {
    Write-Host "  +-------------------------------------+" -ForegroundColor White
    Write-Host "  | Server:   $sqlServer" -ForegroundColor White
    Write-Host "  | Database: $sqlDatabase" -ForegroundColor White
    Write-Host "  | Auth:     $(if ($sqlUser) { "SQL ($sqlUser)" } else { 'Windows' })" -ForegroundColor White
    Write-Host "  +-------------------------------------+" -ForegroundColor White
} else {
    Write-Host "  +-------------------------------------+" -ForegroundColor White
    Write-Host "  | SQL discovery deferred to agent     |" -ForegroundColor Gray
    Write-Host "  | (no PMS detected on this machine)   |" -ForegroundColor Gray
    Write-Host "  +-------------------------------------+" -ForegroundColor White
}

# ============================================
# PHASE 3: Download agent binaries
# ============================================
Write-Step "Phase 3: Downloading SuavoAgent binaries"

New-Item -ItemType Directory -Path $installDir -Force | Out-Null
New-Item -ItemType Directory -Path "$dataDir\logs" -Force | Out-Null

# HIPAA 164.312(a)(2)(iv) — lock down data dir to SYSTEM + LocalService +
# NetworkService (Broker) + Administrators. Runtime service account lacks
# WRITE_DAC so this is the one-and-only place the DACL gets pinned.
try {
    $dataAcl = Get-Acl $dataDir
    $dataAcl.SetAccessRuleProtection($true, $false) # strip inherited rules
    $rules = @(
        (New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\SYSTEM", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")),
        (New-Object System.Security.AccessControl.FileSystemAccessRule(
            "BUILTIN\Administrators", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")),
        (New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\LOCAL SERVICE", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")),
        (New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\NETWORK SERVICE", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow"))
    )
    foreach ($rule in $rules) { $dataAcl.AddAccessRule($rule) }
    Set-Acl $dataDir $dataAcl
    Write-Ok "Data dir ACL locked down ($dataDir)"
} catch {
    Write-Fail "Failed to lock data dir ACL: $($_.Exception.Message)"
    throw
}

# Download and verify checksums
$checksumUrl = "$base/checksums.sha256"
$checksumSigUrl = "$base/checksums.sha256.sig"
$checksumPath = Join-Path $installDir "checksums.sha256"
$checksumSigPath = Join-Path $installDir "checksums.sha256.sig"

Write-Host "  Downloading checksums..." -ForegroundColor Gray
Invoke-WebRequest -Uri $checksumUrl -OutFile $checksumPath -UseBasicParsing
Invoke-WebRequest -Uri $checksumSigUrl -OutFile $checksumSigPath -UseBasicParsing

# Verify ECDSA signature of checksums using only .NET Framework 4.6.0-
# compatible primitives — PowerShell 5.1 ships with .NET Framework 4.6.x
# on many pharmacy Windows installs, and several newer APIs crash there:
#   * ImportSubjectPublicKeyInfo          -> .NET 5+ only
#   * [Convert]::FromHexString            -> .NET 5+ only
#   * ECCurve.NamedCurves.nistP256        -> .NET Framework 4.7.2+
#   * VerifyData(bytes,bytes,HashAlgName) -> .NET Framework 4.6.1+, flaky on 4.6
#   * ECDsaCng.VerifyData(DER signature)  -> expects IEEE P1363 raw r||s
# openssl dgst -sign emits binary DER, so we also must parse DER ourselves.
#
# Strategy: build a BCRYPT_ECCKEY_BLOB (available since .NET 3.5 via CngKey.Import),
# hand-convert the DER sig to P1363, and verify a pre-computed SHA-256 hash.

$publicKeyDer = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBLRvZ572EpqNab9CxJ9/b/GfHpHOrhWkpaaCzIkXQ5d2dwiqdJHlxvrgN0/zCsgp/ccnDXed4DFCkh6wUWCvWA=="
$derBytes = [System.Convert]::FromBase64String($publicKeyDer)
if ($derBytes.Length -lt 65 -or $derBytes[$derBytes.Length - 65] -ne 0x04) {
    Write-Error "Embedded public key is not a valid P-256 uncompressed point"
    exit 1
}
$qx = New-Object byte[] 32
$qy = New-Object byte[] 32
[Array]::Copy($derBytes, $derBytes.Length - 64, $qx, 0, 32)
[Array]::Copy($derBytes, $derBytes.Length - 32, $qy, 0, 32)

# BCRYPT_ECCKEY_BLOB layout for a P-256 public key (72 bytes total):
#   dwMagic : uint32 LE = 0x31534345 (BCRYPT_ECDSA_PUBLIC_P256_MAGIC, "ECS1")
#   cbKey   : uint32 LE = 32 (size of each coordinate for P-256)
#   X[32], Y[32]
$blob = New-Object byte[] 72
$blob[0] = 0x45; $blob[1] = 0x43; $blob[2] = 0x53; $blob[3] = 0x31  # "ECS1" LE
$blob[4] = 0x20; $blob[5] = 0x00; $blob[6] = 0x00; $blob[7] = 0x00  # cbKey=32 LE
[Array]::Copy($qx, 0, $blob, 8, 32)
[Array]::Copy($qy, 0, $blob, 40, 32)

$cngKey = [System.Security.Cryptography.CngKey]::Import(
    $blob,
    [System.Security.Cryptography.CngKeyBlobFormat]::EccPublicBlob)
$ecdsa = New-Object System.Security.Cryptography.ECDsaCng($cngKey)

$checksumBytes = [System.IO.File]::ReadAllBytes($checksumPath)
$sigBytes      = [System.IO.File]::ReadAllBytes($checksumSigPath)

# Convert DER ECDSA signature to IEEE P1363 (raw r||s, 64 bytes for P-256).
# DER layout: 30 <seqLen> 02 <rLen> <r-bytes> 02 <sLen> <s-bytes>
# r/s each may carry a leading 0x00 sign-bit padding byte from DER encoding.
if ($sigBytes.Length -lt 8 -or $sigBytes[0] -ne 0x30) {
    Write-Error "Signature is not a valid DER SEQUENCE"
    exit 1
}
$seqHdrLen = 2
if (($sigBytes[1] -band 0x80) -ne 0) {
    $seqHdrLen = 2 + ($sigBytes[1] -band 0x7F)
}
if ($sigBytes[$seqHdrLen] -ne 0x02) {
    Write-Error "Signature missing r INTEGER tag"
    exit 1
}
$rLenOrig = [int]$sigBytes[$seqHdrLen + 1]
$rStart   = $seqHdrLen + 2
$rEnd     = $rStart + $rLenOrig

if ($sigBytes[$rEnd] -ne 0x02) {
    Write-Error "Signature missing s INTEGER tag"
    exit 1
}
$sLenOrig = [int]$sigBytes[$rEnd + 1]
$sStart   = $rEnd + 2
$sEnd     = $sStart + $sLenOrig

if ($sEnd -ne $sigBytes.Length) {
    Write-Error "Signature DER length mismatch (expected $($sigBytes.Length), got $sEnd)"
    exit 1
}

$rLen = $rLenOrig
while ($rLen -gt 0 -and $sigBytes[$rStart] -eq 0) { $rStart++; $rLen-- }
$sLen = $sLenOrig
while ($sLen -gt 0 -and $sigBytes[$sStart] -eq 0) { $sStart++; $sLen-- }
if ($rLen -gt 32 -or $sLen -gt 32) {
    Write-Error "Signature r or s exceeds 32 bytes after stripping padding"
    exit 1
}

$p1363 = New-Object byte[] 64
[Array]::Copy($sigBytes, $rStart, $p1363, 32 - $rLen, $rLen)
[Array]::Copy($sigBytes, $sStart, $p1363, 64 - $sLen, $sLen)

# VerifyHash is the most portable path — avoids HashAlgorithmName overload
# differences between 4.6.x point releases.
$sha256 = [System.Security.Cryptography.SHA256]::Create()
$hash   = $sha256.ComputeHash($checksumBytes)
$valid  = $ecdsa.VerifyHash($hash, $p1363)

if (-not $valid) {
    Write-Error "CRITICAL: Checksum signature verification FAILED - aborting install"
    Remove-Item $checksumPath, $checksumSigPath -Force -ErrorAction SilentlyContinue
    exit 1
}
Write-Host "  Checksum signature verified (ECDSA P-256)" -ForegroundColor Green

# Parse expected hashes
$expectedHashes = @{}
Get-Content $checksumPath | ForEach-Object {
    $parts = $_ -split "  ", 2
    if ($parts.Count -eq 2) { $expectedHashes[$parts[1].Trim()] = $parts[0].Trim() }
}

$binaries = @("SuavoAgent.Core.exe", "SuavoAgent.Broker.exe", "SuavoAgent.Helper.exe")

# Verify ALL expected binaries have checksum entries before downloading anything
foreach ($bin in $binaries) {
    if (-not $expectedHashes.ContainsKey($bin)) {
        Write-Error "CRITICAL: Checksum missing for $bin -- aborting install"
        exit 1
    }
}

foreach ($bin in $binaries) {
    $url = "$base/$bin"
    $dst = Join-Path $installDir $bin
    Write-Host "  Downloading $bin..." -ForegroundColor Gray
    try {
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $url -OutFile $dst -UseBasicParsing
        $sizeMb = [math]::Round((Get-Item $dst).Length / 1MB, 1)
        Write-Ok "$bin ($sizeMb MB)"
    } catch {
        Write-Fail "Download failed for $bin -- $($_.Exception.Message)"
        exit 1
    }
    # Verify SHA256 hash against signed checksums
    $actualHash = (Get-FileHash -Path $dst -Algorithm SHA256).Hash.ToLower()
    if ($expectedHashes.ContainsKey($bin) -and $actualHash -ne $expectedHashes[$bin]) {
        Write-Error "CRITICAL: SHA256 mismatch for $bin - expected $($expectedHashes[$bin]), got $actualHash"
        foreach ($b in $binaries) { Remove-Item (Join-Path $installDir $b) -Force -ErrorAction SilentlyContinue }
        exit 1
    }
    Write-Host "  $bin verified: $actualHash" -ForegroundColor Green
}

# ============================================
# SECURITY CHECK: BitLocker Status
# ============================================
Write-Step "Security: Checking disk encryption"
$bitlockerStatus = $null
try {
    $bitlockerStatus = (manage-bde -status $env:SystemDrive 2>$null | Select-String "Protection Status").ToString()
} catch { }

if ($bitlockerStatus -and $bitlockerStatus -match "Protection On") {
    Write-Ok "BitLocker is ENABLED on $env:SystemDrive — HIPAA breach safe harbor active"
} else {
    Write-Warn "BitLocker is NOT enabled on $env:SystemDrive"
    Write-Host "  HIPAA RECOMMENDATION: Enable BitLocker for full-disk encryption" -ForegroundColor Yellow
    Write-Host "  Without BitLocker, a stolen computer = reportable HIPAA breach" -ForegroundColor Yellow
    Write-Host "  Delivery receipts are encrypted by SuavoAgent (DPAPI) regardless" -ForegroundColor Gray
    Write-Host ""
}

# ============================================
# PHASE 4: Write appsettings.json
# ============================================
Write-Step "Phase 4: Writing configuration"

$fingerprint = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Cryptography').MachineGuid

# -- Register with cloud via install token (dashboard onboarding path) --
if ($InstallToken -and -not $ApiKey) {
    Write-Step "Registering agent with cloud using install token..."
    try {
        $machineName = [System.Net.Dns]::GetHostName()
        $registerBody = @{
            licenseKey = ""  # Install-token flow doesn't need licenseKey
            installToken = $InstallToken
            machineName = $machineName
            machineFingerprint = $fingerprint
            agentVersion = $ReleaseTag.TrimStart('v')
        } | ConvertTo-Json -Depth 3
        $registerResp = Invoke-RestMethod `
            -Uri "$CloudUrl/api/agent/register" `
            -Method POST `
            -ContentType "application/json" `
            -Body $registerBody `
            -TimeoutSec 30
        if (-not $registerResp.success) {
            throw "Cloud rejected registration: $($registerResp.error)"
        }
        $ApiKey = $registerResp.data.apiKey
        $PharmacyId = $registerResp.data.pharmacyId
        Write-Ok "Registered as pharmacy $PharmacyId"
    } catch {
        Write-Fail "Registration failed: $($_.Exception.Message)"
        exit 1
    }
}

$agentId = "agent-" + ([guid]::NewGuid().ToString("N").Substring(0, 12))

$config = @{
    Agent = @{
        CloudUrl = $CloudUrl
        ApiKey = $ApiKey
        AgentId = $agentId
        PharmacyId = $PharmacyId
        MachineFingerprint = $fingerprint
        Version = $ReleaseTag.TrimStart('v')
        SqlServer = $sqlServer
        SqlDatabase = $sqlDatabase
        LearningMode = [bool]$LearningMode
    }
}
if ($sqlUser) {
    $config.Agent.SqlUser = $sqlUser
    $config.Agent.SqlPassword = $sqlPassword
}

$configJson = $config | ConvertTo-Json -Depth 5
$configPath = Join-Path $installDir "appsettings.json"
Set-Content -Path $configPath -Value $configJson -Encoding UTF8

# Write consent receipt to ProgramData — uploaded to cloud on first heartbeat
$consentPath = Join-Path $dataDir "consent-receipt.json"
$consentReceipt.pharmacyId = $PharmacyId
$consentReceipt.agentId = $agentId
$consentJson = $consentReceipt | ConvertTo-Json -Depth 5
Set-Content -Path $consentPath -Value $consentJson -Encoding UTF8
Write-Ok "Consent receipt saved to $consentPath"
Write-Ok "appsettings.json written to $installDir"

# Lock down appsettings (contains SQL credentials)
$acl = Get-Acl $configPath
$acl.SetAccessRuleProtection($true, $false)
$acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "BUILTIN\Administrators", "FullControl", "None", "None", "Allow")))
$acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "NT AUTHORITY\SYSTEM", "FullControl", "None", "None", "Allow")))
$acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "NT AUTHORITY\LOCAL SERVICE", "Read", "None", "None", "Allow")))
Set-Acl $configPath $acl
Write-Ok "Credentials locked down (Admin + SYSTEM + LocalService only)"

# ============================================
# PHASE 5: Install Windows services
# ============================================
Write-Step "Phase 5: Installing Windows services"

# Stop + remove existing
foreach ($svc in @("SuavoAgent.Broker", "SuavoAgent.Core")) {
    $s = Get-Service -Name $svc -ErrorAction SilentlyContinue
    if ($s) {
        if ($s.Status -eq "Running") { Stop-Service $svc -Force; Start-Sleep 2 }
        sc.exe delete $svc 2>$null | Out-Null
        Start-Sleep 1
    }
}

# Install Core (runs as LocalService -- least privilege)
$corePath = Join-Path $installDir "SuavoAgent.Core.exe"
sc.exe create SuavoAgent.Core binPath= "`"$corePath`"" start= delayed-auto obj= "NT AUTHORITY\LocalService" | Out-Null
sc.exe description SuavoAgent.Core "Suavo pharmacy agent - SQL polling, cloud sync" | Out-Null
sc.exe failure SuavoAgent.Core reset= 3600 actions= restart/5000/restart/30000/restart/60000 | Out-Null
sc.exe failureflag SuavoAgent.Core 1 | Out-Null
Write-Ok "SuavoAgent.Core service registered"

# Install Broker (runs as NetworkService -- needs SeTcbPrivilege for WTSQueryUserToken + CreateProcessAsUser)
$brokerPath = Join-Path $installDir "SuavoAgent.Broker.exe"
sc.exe create SuavoAgent.Broker binPath= "`"$brokerPath`"" start= delayed-auto obj= "NT AUTHORITY\NetworkService" | Out-Null
sc.exe description SuavoAgent.Broker "Suavo pharmacy agent - session broker" | Out-Null
sc.exe failure SuavoAgent.Broker reset= 3600 actions= restart/5000/restart/30000/restart/60000 | Out-Null
sc.exe failureflag SuavoAgent.Broker 1 | Out-Null
sc.exe config SuavoAgent.Broker depend= SuavoAgent.Core | Out-Null
Write-Ok "SuavoAgent.Broker service registered"

# Lock down install directory
$dirAcl = Get-Acl $installDir
$dirAcl.SetAccessRuleProtection($true, $false)
$dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "BUILTIN\Administrators", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")))
$dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "NT AUTHORITY\SYSTEM", "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")))
$dirAcl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
    "NT AUTHORITY\LOCAL SERVICE", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow")))
Set-Acl $installDir $dirAcl

# Start services. Start-Service's 30s default wait is tight for cold starts
# on .NET 8 single-file self-extracting exes, so we poll manually up to 90s
# and — if the service still isn't Running — capture a full post-mortem to
# the operator's Desktop. That way we don't have to ping-pong PowerShell
# diagnostic commands through the operator when something breaks.
function Wait-ServiceRunning {
    param([string]$Name, [int]$TimeoutSec = 90)
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        $svc = Get-Service -Name $Name -ErrorAction SilentlyContinue
        if ($svc -and $svc.Status -eq 'Running') { return $true }
        Start-Sleep -Seconds 2
    }
    return $false
}

function Save-StartupPostmortem {
    param([string]$ServiceName, [string]$DumpPath)
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("SuavoAgent service start post-mortem")
    $lines.Add("Service: $ServiceName")
    $lines.Add("Timestamp: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')")
    $lines.Add("Machine: $env:COMPUTERNAME")
    $lines.Add("Release: $ReleaseTag")
    $lines.Add("")
    $lines.Add("=== Get-Service ===")
    try {
        $svc = Get-Service -Name $ServiceName -ErrorAction Stop
        $lines.Add(($svc | Format-List Name,Status,StartType,DisplayName | Out-String).Trim())
    } catch { $lines.Add("Get-Service failed: $($_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== sc.exe qc (config) ===")
    try {
        $qc = sc.exe qc $ServiceName 2>&1 | Out-String
        $lines.Add($qc.Trim())
    } catch { $lines.Add("sc qc failed: $($_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== sc.exe queryex (state + exit code) ===")
    try {
        $qex = sc.exe queryex $ServiceName 2>&1 | Out-String
        $lines.Add($qex.Trim())
    } catch { $lines.Add("sc queryex failed: $($_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== Recent System log (SCM) ===")
    try {
        $sys = Get-WinEvent -FilterHashtable @{
            LogName      = 'System'
            ProviderName = 'Service Control Manager'
            StartTime    = (Get-Date).AddMinutes(-10)
        } -ErrorAction SilentlyContinue |
            Where-Object { $_.Message -match 'Suavo' } |
            Select-Object -First 10
        if ($sys) { $lines.Add(($sys | Format-List TimeCreated,LevelDisplayName,Id,Message | Out-String).Trim()) }
        else { $lines.Add("(no SCM events matching 'Suavo' in the last 10 min)") }
    } catch { $lines.Add("System log query failed: $($_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== Recent Application log (.NET Runtime + Application Error) ===")
    try {
        $app = Get-WinEvent -FilterHashtable @{
            LogName   = 'Application'
            StartTime = (Get-Date).AddMinutes(-10)
        } -ErrorAction SilentlyContinue |
            Where-Object { $_.ProviderName -match '\.NET Runtime|Application Error|\.NET Host' -or $_.Message -match 'Suavo' } |
            Select-Object -First 15
        if ($app) { $lines.Add(($app | Format-List TimeCreated,LevelDisplayName,ProviderName,Id,Message | Out-String).Trim()) }
        else { $lines.Add("(no matching Application events in the last 10 min)") }
    } catch { $lines.Add("Application log query failed: $($_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== Agent install dir listing ===")
    try {
        $ls = Get-ChildItem $installDir -Force | Select-Object Name, Length, LastWriteTime | Format-Table | Out-String
        $lines.Add($ls.Trim())
    } catch { $lines.Add("install dir listing failed: $($_.Exception.Message)") }
    $lines.Add("")
    $lines.Add("=== Core startup-crash.log (written by last-resort crash sink) ===")
    $crashLog = Join-Path $env:ProgramData "SuavoAgent\logs\startup-crash.log"
    if (Test-Path $crashLog) {
        try { $lines.Add((Get-Content $crashLog -Raw).Trim()) }
        catch { $lines.Add("crash log read failed: $($_.Exception.Message)") }
    } else {
        $lines.Add("(startup-crash.log not present — process died before crash sink ran)")
    }
    $lines.Add("")
    $lines.Add("=== Core Serilog startup-YYYYMMDD.log (last 80 lines) ===")
    $startupLogDir = Join-Path $env:ProgramData "SuavoAgent\logs"
    if (Test-Path $startupLogDir) {
        $latest = Get-ChildItem $startupLogDir -Filter 'startup-*.log' -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending | Select-Object -First 1
        if ($latest) {
            try { $lines.Add((Get-Content $latest.FullName -Tail 80 | Out-String).Trim()) }
            catch { $lines.Add("startup log read failed: $($_.Exception.Message)") }
        } else {
            $lines.Add("(no startup-*.log found)")
        }
    } else {
        $lines.Add("(ProgramData\SuavoAgent\logs not present — service never reached Serilog init)")
    }

    $text = ($lines -join [Environment]::NewLine)
    [System.IO.File]::WriteAllText($DumpPath, $text)
}

Write-Host "  Starting SuavoAgent.Core (up to 90s)..." -ForegroundColor Gray
try { Start-Service SuavoAgent.Core -ErrorAction Stop } catch {
    # Start-Service can throw even when the service is in StartPending;
    # swallow here and let the poll below be the source of truth.
}
if (Wait-ServiceRunning -Name 'SuavoAgent.Core' -TimeoutSec 90) {
    Write-Ok "SuavoAgent.Core is running"
} else {
    $dumpPath = Join-Path $env:USERPROFILE "Desktop\suavo-service-postmortem-$(Get-Date -Format 'yyyyMMdd-HHmmss').txt"
    Save-StartupPostmortem -ServiceName 'SuavoAgent.Core' -DumpPath $dumpPath
    Write-Fail "SuavoAgent.Core did not reach Running within 90s"
    Write-Host "  Post-mortem saved to: $dumpPath" -ForegroundColor Yellow
    Write-Host "  Send that file to whoever is helping and they will have everything needed to diagnose." -ForegroundColor Yellow
}

Write-Host "  Starting SuavoAgent.Broker..." -ForegroundColor Gray
try { Start-Service SuavoAgent.Broker -ErrorAction Stop } catch { }
if (-not (Wait-ServiceRunning -Name 'SuavoAgent.Broker' -TimeoutSec 60)) {
    $brokerDump = Join-Path $env:USERPROFILE "Desktop\suavo-broker-postmortem-$(Get-Date -Format 'yyyyMMdd-HHmmss').txt"
    Save-StartupPostmortem -ServiceName 'SuavoAgent.Broker' -DumpPath $brokerDump
    Write-Host "  Broker did not start within 60s — post-mortem at $brokerDump" -ForegroundColor Yellow
}

# ============================================
# PHASE 6: Verify
# ============================================
Write-Step "Phase 6: Verification"

foreach ($svc in @("SuavoAgent.Core", "SuavoAgent.Broker")) {
    $s = Get-Service -Name $svc -ErrorAction SilentlyContinue
    if ($s -and $s.Status -eq "Running") {
        Write-Ok "$svc is running"
    } else {
        Write-Warn "$svc status: $($s.Status)"
    }
}

Write-Host ""
Write-Host "  +===========================================+" -ForegroundColor Green
Write-Host "  |   SuavoAgent v3 -- Installation Complete   |" -ForegroundColor Green
Write-Host "  +===========================================+" -ForegroundColor Green
Write-Host ""
Write-Host "  Install:  $installDir" -ForegroundColor White
Write-Host "  Data:     $dataDir" -ForegroundColor White
Write-Host "  Logs:     $dataDir\logs\" -ForegroundColor White
Write-Host "  Config:   $configPath" -ForegroundColor White
Write-Host "  Agent ID: $agentId" -ForegroundColor White
Write-Host ""
if ($sqlServer) {
    Write-Host "  SQL:      $sqlServer / $sqlDatabase" -ForegroundColor White
    Write-Host "  Auth:     $(if ($sqlUser) { "SQL ($sqlUser)" } else { 'Windows' })" -ForegroundColor White
} else {
    Write-Host "  SQL:      (deferred — agent will auto-discover during learning phase)" -ForegroundColor Gray
}
Write-Host ""

Get-ChildItem "$installDir\*.exe" | ForEach-Object {
    $sizeMb = [math]::Round($_.Length / 1MB, 1)
    Write-Host "  $($_.Name) -- $sizeMb MB" -ForegroundColor Gray
}

Write-Host ""
Write-Host "  Agent will query for delivery-ready Rxs every 5 minutes." -ForegroundColor Cyan
Write-Host "  Check logs: Get-Content $dataDir\logs\core-*.log -Tail 50" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Install log: $transcriptPath" -ForegroundColor Gray

# Clean up install transcript on success
try {
    Stop-Transcript -ErrorAction SilentlyContinue | Out-Null
    if ($transcriptPath -and (Test-Path $transcriptPath)) {
        Remove-Item $transcriptPath -Force -ErrorAction SilentlyContinue
        Write-Ok "Install transcript cleaned up"
    }
} catch { }
