using SuavoAgent.Contracts.Models;
using Xunit;

namespace SuavoAgent.Contracts.Tests.Models;

// Codex 2026-04-26 audit fix: SendPatientDetailsAsync used to take an opaque
// `object details` and the only caller passed RxPatientDetails — which
// includes RxNumber as a cleartext field even though the hashed version was
// already the routing key. PatientDetailsPayload is the deliberate typed
// contract. Pin the projection so a future refactor can't silently start
// shipping fields that don't belong on the wire.
public class PatientDetailsPayloadTests
{
    [Fact]
    public void FromRxPatientDetails_ProjectsAllDeliveryFields()
    {
        var source = new RxPatientDetails(
            RxNumber: "RX12345678",
            FirstName: "Jane",
            LastInitial: "D",
            Phone: "555-123-4567",
            Address1: "123 Main St",
            Address2: "Apt 4",
            City: "San Diego",
            State: "CA",
            Zip: "92101");

        var payload = PatientDetailsPayload.FromRxPatientDetails(source);

        Assert.Equal("Jane", payload.FirstName);
        Assert.Equal("D", payload.LastInitial);
        Assert.Equal("555-123-4567", payload.Phone);
        Assert.Equal("123 Main St", payload.Address1);
        Assert.Equal("Apt 4", payload.Address2);
        Assert.Equal("San Diego", payload.City);
        Assert.Equal("CA", payload.State);
        Assert.Equal("92101", payload.Zip);
    }

    [Fact]
    public void FromRxPatientDetails_DropsRxNumber()
    {
        var source = new RxPatientDetails(
            RxNumber: "RX99999999",
            FirstName: "X",
            LastInitial: null,
            Phone: null,
            Address1: null,
            Address2: null,
            City: null,
            State: null,
            Zip: null);

        var payload = PatientDetailsPayload.FromRxPatientDetails(source);

        // Compile-time guarantee: PatientDetailsPayload has no RxNumber
        // property. This test exists to catch a future refactor that adds
        // one back via "convenience" — would fail with a compile error
        // here at the property access if RxNumber were re-added.
        var properties = typeof(PatientDetailsPayload).GetProperties();
        Assert.DoesNotContain(properties, p => p.Name == "RxNumber");
    }

    [Fact]
    public void Record_HasOnlyDriverNeededFields()
    {
        // Pin the exact field list. Any new PHI field shipped to cloud has
        // to land here first, which makes the diff impossible to miss in
        // code review. Adding fields requires explicitly updating this test.
        // EqualityContract is auto-generated by record types — exclude.
        var properties = typeof(PatientDetailsPayload)
            .GetProperties()
            .Where(p => p.Name != "EqualityContract")
            .Select(p => p.Name)
            .OrderBy(n => n)
            .ToArray();

        Assert.Equal(
            new[] { "Address1", "Address2", "City", "FirstName", "LastInitial", "Phone", "State", "Zip" },
            properties);
    }
}
