#!/usr/bin/env bash
set -euo pipefail

# Exportable PEM release signing was retired. Production OTA manifests are
# generated by the protected release/hotfix workflows and signed by the
# non-exportable ota-update-v1 AWS KMS key through GitHub OIDC. Keeping a local
# upload fallback would bypass environment reviewers, attestations, the exact
# Authenticode signer allowlist, and the clean-build provenance chain.
echo "Local OTA release signing is disabled. Use the protected SuavoAgent production release workflow." >&2
exit 2
